document.write('<section class="row_am latest_story blog_list_story">');
document.write('      <div class="container">');
document.write('        <div class="row">');
document.write('          <div class="col-6">');
document.write('            <h2 class="mb-3">Últimos blogs</h2>');
document.write('          </div>');
document.write('          <div class="col-6 text-right">');
document.write('            <a class="btn btn-primary mb-3 mr-1" href="#carouselExampleIndicators2" role="button" data-slide="prev"');
document.write('              style="background-color: #32236F; border-color: #32236F;">');
document.write('              <i class="fa fa-arrow-left"></i>');
document.write('            </a>');
document.write('            <a class="btn btn-primary mb-3 " href="#carouselExampleIndicators2" role="button" data-slide="next"');
document.write('              style="background-color: #32236F; border-color: #32236F;">');
document.write('              <i class="fa fa-arrow-right"></i>');
document.write('            </a>');
document.write('          </div>');
document.write('          <div class="col-12">');
document.write('            <div id="carouselExampleIndicators2" class="carousel slide" data-ride="carousel">');
document.write('');
document.write('              <div class="carousel-inner">');
document.write('');
document.write('');
document.write('                <div class="carousel-item active">');
document.write('                  <div class="row">');
document.write('');
document.write('                    <!-- story -->');
document.write('                    <div class="col-md-4">');
document.write('                      <div class="story_box">');
document.write('                        <div class="story_img">');
document.write('                          <img src="https://catchup.cloud/portuguese/blog/images/blog1.jpg" alt="image">');
document.write('');
document.write('                        </div>');
document.write('                        <div class="story_text">');
document.write('                          <a href="https://catchup.cloud/portuguese/blog/blog_how_project_management_tool_can_enhance_office_productivity.html">');
document.write('                            <h3>Como uma ferramenta de gerenciamento de projetos pode aumentar a produtividade do seu escritório?');
document.write('                            </h3>');
document.write('                          </a>');
document.write('                          <p>No mundo dos negócios de hoje, o gerenciamento eficaz de projetos é essencial para o sucesso...</p>');
document.write('                          <a href="https://catchup.cloud/portuguese/blog/blog_how_project_management_tool_can_enhance_office_productivity.html">VER COMPLETO</a>');
document.write('                        </div>');
document.write('                      </div>');
document.write('                    </div>');
document.write('');
document.write('                    <!-- story -->');
document.write('                    <div class="col-md-4">');
document.write('                      <div class="story_box">');
document.write('                        <div class="story_img">');
document.write('                          <img src="https://catchup.cloud/portuguese/blog/images/blog2.jpg" alt="image">');
document.write('');
document.write('                        </div>');
document.write('                        <div class="story_text">');
document.write('                          <a href="https://catchup.cloud/portuguese/blog/blog_what_features_to_look_for_in_project_management_tool.html">');
document.write('                            <h3>Quais recursos procurar em uma ferramenta de gerenciamento de projetos?');
document.write('                            </h3>');
document.write('                          </a>');
document.write('                          <p>Para garantir a máxima eficiência, certos recursos obrigatórios devem ser considerados ao selecionar uma ferramenta de gerenciamento de projetos...');
document.write('                          </p>');
document.write('                          <a href="https://catchup.cloud/portuguese/blog/blog_what_features_to_look_for_in_project_management_tool.html">VER COMPLETO</a>');
document.write('                        </div>');
document.write('                      </div>');
document.write('                    </div>');
document.write('');
document.write('                    <!-- story -->');
document.write('                    <div class="col-md-4">');
document.write('                      <div class="story_box">');
document.write('                        <div class="story_img">');
document.write('                          <img src="https://catchup.cloud/portuguese/blog/images/blog3.jpg" alt="image">');
document.write('');
document.write('                        </div>');
document.write('                        <div class="story_text">');
document.write('                          <a href="https://catchup.cloud/portuguese/blog/blog_why_you_should_use_a_project_management_tool.html">');
document.write('                            <h3>Por que você deve usar uma ferramenta de gerenciamento de projetos?');
document.write('                            </h3>');
document.write('                          </a>');
document.write('                          <p>Um sistema de gerenciamento de projetos é uma ferramenta valiosa para qualquer organização. Ele pode ajudá-lo a otimizar seu fluxo de trabalho...');
document.write('                          </p>');
document.write('                          <a href="https://catchup.cloud/portuguese/blog/blog_why_you_should_use_a_project_management_tool.html">VER COMPLETO</a>');
document.write('                        </div>');
document.write('                      </div>');
document.write('                    </div>');
document.write('');
document.write('');
document.write('                  </div>');
document.write('                </div>');
document.write('');
document.write('                <div class="carousel-item">');
document.write('                  <div class="row">');
document.write('');
document.write('                    <!-- story -->');
document.write('                    <div class="col-md-4">');
document.write('                      <div class="story_box">');
document.write('                        <div class="story_img">');
document.write('                          <img src="https://catchup.cloud/portuguese/blog/images/blog6.jpg" alt="image">');
document.write('');
document.write('                        </div>');
document.write('                        <div class="story_text">');
document.write('                          <a href="https://catchup.cloud/portuguese/blog/blog_how_kanban_helps_teams_be_productive.html">');
document.write('                            <h3>Como o Kanban ajuda as equipes a serem produtivas?');
document.write('                            </h3>');
document.write('                          </a>');
document.write('                          <p>Kanban é uma metodologia para planejar, programar e aprimorar o trabalho em sistemas...</p>');
document.write('                          <a href="https://catchup.cloud/portuguese/blog/blog_how_kanban_helps_teams_be_productive.html">VER COMPLETO</a>');
document.write('                        </div>');
document.write('                      </div>');
document.write('                    </div>');
document.write('');
document.write('                    <!-- story -->');
document.write('                    <div class="col-md-4">');
document.write('                      <div class="story_box">');
document.write('                        <div class="story_img">');
document.write('                          <img src="https://catchup.cloud/portuguese/blog/images/blog5.jpg" alt="image">');
document.write('');
document.write('                        </div>');
document.write('                        <div class="story_text">');
document.write('                          <a href="https://catchup.cloud/portuguese/blog/blog_what_is_a_project_management_software.html">');
document.write('                            <h3>O que é um software de gerenciamento de projetos e por que você precisa dele?');
document.write('                            </h3>');
document.write('                          </a>');
document.write('                          <p>Um software de gerenciamento de projetos é uma ferramenta que ajuda as organizações a planejar...</p>');
document.write('                          <a href="https://catchup.cloud/portuguese/blog/blog_what_is_a_project_management_software.html">VER COMPLETO</a>');
document.write('                        </div>');
document.write('                      </div>');
document.write('                    </div>');
document.write('');
document.write('                    <!-- story -->');
document.write('                    <div class="col-md-4">');
document.write('                      <div class="story_box">');
document.write('                        <div class="story_img">');
document.write('                          <img src="https://catchup.cloud/portuguese/blog/images/blog4.jpg" alt="image">');
document.write('');
document.write('                        </div>');
document.write('                        <div class="story_text">');
document.write('                          <a href="https://catchup.cloud/portuguese/blog/blog_your_guide_to_effective_project_management.html">');
document.write('                            <h3>Seu guia para um gerenciamento de projetos eficaz');
document.write('                            </h3>');
document.write('                          </a>');
document.write('                          <p>Um projeto é uma coleção de tarefas que devem ser concluídas em um prazo específico...</p>');
document.write('                          <a href="https://catchup.cloud/portuguese/blog/blog_your_guide_to_effective_project_management.html">VER COMPLETO</a>');
document.write('                        </div>');
document.write('                      </div>');
document.write('                    </div>');
document.write('');
document.write('');
document.write('                  </div>');
document.write('                </div>');
document.write('');
document.write('                <div class="carousel-item">');
document.write('                  <div class="row">');
document.write('');
document.write('                    <!-- story -->');
document.write('                    <div class="col-md-4">');
document.write('                      <div class="story_box">');
document.write('                        <div class="story_img">');
document.write('                          <img src="https://catchup.cloud/portuguese/blog/images/blog9.jpg" alt="image">');
document.write('');
document.write('                        </div>');
document.write('                        <div class="story_text">');
document.write('                          <a href="https://catchup.cloud/portuguese/blog/blog_top_5_tips_for_effective_project_management.html">');
document.write('                            <h3>As 5 principais dicas para um gerenciamento de projetos eficaz ');
document.write('                            </h3>');
document.write('                          </a>');
document.write('                          <p>Obter serviços e produtos de qualidade entregues dentro de um determinado prazo e orçamento é a necessidade de qualquer empresa...</p>');
document.write('                          <a href="https://catchup.cloud/portuguese/blog/blog_top_5_tips_for_effective_project_management.html">VER COMPLETO</a>');
document.write('                        </div>');
document.write('                      </div>');
document.write('                    </div>');
document.write('');
document.write('                    <!-- story -->');
document.write('                    <div class="col-md-4">');
document.write('                      <div class="story_box">');
document.write('                        <div class="story_img">');
document.write('                          <img src="https://catchup.cloud/portuguese/blog/images/blog8.jpg" alt="image">');
document.write('');
document.write('                        </div>');
document.write('                        <div class="story_text">');
document.write('                          <a href="https://catchup.cloud/portuguese/blog/blog_top_5_best_practices_for_remote_work_management.html">');
document.write('                            <h3>As 5 melhores práticas para gerenciamento de trabalho remoto');
document.write('                            </h3>');
document.write('                          </a>');
document.write('                          <p>O trabalho remoto tornou-se uma norma no mundo atual e é essencial para as organizações...');
document.write('                          </p>');
document.write('                          <a href="https://catchup.cloud/portuguese/blog/blog_top_5_best_practices_for_remote_work_management.html">VER COMPLETO</a>');
document.write('                        </div>');
document.write('                      </div>');
document.write('                    </div>');
document.write('');
document.write('                    <!-- story -->');
document.write('                    <div class="col-md-4">');
document.write('                      <div class="story_box">');
document.write('                        <div class="story_img">');
document.write('                          <img src="https://catchup.cloud/portuguese/blog/images/blog7.jpg" alt="image">');
document.write('');
document.write('                        </div>');
document.write('                        <div class="story_text">');
document.write('                          <a href="https://catchup.cloud/portuguese/blog/blog_top_10_remote_work_management_mistakes_and_how_to_avoid_them.html">');
document.write('                            <h3>Os 10 principais erros de gerenciamento de trabalho remoto e como evitá-los');
document.write('                            </h3>');
document.write('                          </a>');
document.write('                          <p>À medida que o trabalho remoto se torna mais popular, um número crescente de...</p>');
document.write('                          <a href="https://catchup.cloud/portuguese/blog/blog_top_10_remote_work_management_mistakes_and_how_to_avoid_them.html">VER COMPLETO</a>');
document.write('                        </div>');
document.write('                      </div>');
document.write('                    </div>');
document.write('');
document.write('');
document.write('                  </div>');
document.write('                </div>');
document.write('');
document.write('                <div class="carousel-item">');
document.write('                  <div class="row">');
document.write('');
document.write('                    <!-- story -->');
document.write('                    <div class="col-md-4">');
document.write('                      <div class="story_box">');
document.write('                        <div class="story_img">');
document.write('                          <img src="https://catchup.cloud/portuguese/blog/images/blog12.jpg" alt="image">');
document.write('');
document.write('                        </div>');
document.write('                        <div class="story_text">');
document.write('                          <a href="https://catchup.cloud/portuguese/blog/blog_understanding_cobra_typology_for_brand_growth.html">');
document.write('                            <h3>Compreendendo a Tipologia COBRA (comportamentos relacionados à marca on-line dos clientes) para o crescimento da marca');
document.write('                            </h3>');
document.write('                          </a>');
document.write('                          <p>Empresas ativas no espaço digital...</p>');
document.write('                          <a href="https://catchup.cloud/portuguese/blog/blog_understanding_cobra_typology_for_brand_growth.html">VER COMPLETO</a>');
document.write('                        </div>');
document.write('                      </div>');
document.write('                    </div>');
document.write('');
document.write('');
document.write('                    <!-- story -->');
document.write('                    <div class="col-md-4">');
document.write('                      <div class="story_box">');
document.write('                        <div class="story_img">');
document.write('                          <img src="https://catchup.cloud/portuguese/blog/images/blog11.jpg" alt="image">');
document.write('');
document.write('                        </div>');
document.write('                        <div class="story_text">');
document.write('                          <a');
document.write('                            href="https://catchup.cloud/portuguese/blog/blog_how_a_good_project_management_tool_helps_manage_transformation_expenditures.html">');
document.write('                            <h3>Como uma boa ferramenta de gerenciamento de projetos ajuda a gerenciar as despesas de transformação?');
document.write('                            </h3>');
document.write('                          </a>');
document.write('                          <p>As despesas de transformação são...</p>');
document.write('                          <a');
document.write('                            href="https://catchup.cloud/portuguese/blog/blog_how_a_good_project_management_tool_helps_manage_transformation_expenditures.html">VER');
document.write('                            COMPLETO</a>');
document.write('                        </div>');
document.write('                      </div>');
document.write('                    </div>');
document.write('');
document.write('                    <!-- story -->');
document.write('                    <div class="col-md-4">');
document.write('                      <div class="story_box">');
document.write('                        <div class="story_img">');
document.write('                          <img src="https://catchup.cloud/portuguese/blog/images/blog10.jpg" alt="image">');
document.write('');
document.write('                        </div>');
document.write('                        <div class="story_text">');
document.write('                          <a href="https://catchup.cloud/portuguese/blog/blog_why_leading_companies_are_prioritizing_digital_transformation.html">');
document.write('                            <h3>Por que as empresas líderes estão priorizando a transformação digital?');
document.write('                            </h3>');
document.write('                          </a>');
document.write('                          <p>A transformação digital é cada vez mais uma prioridade para as empresas...</p>');
document.write('                          <a href="https://catchup.cloud/portuguese/blog/blog_why_leading_companies_are_prioritizing_digital_transformation.html">VER');
document.write('                            COMPLETO</a>');
document.write('                        </div>');
document.write('                      </div>');
document.write('                    </div>');
document.write('');
document.write('');
document.write('                  </div>');
document.write('                </div>');
document.write('');
document.write('                <div class="carousel-item">');
document.write('                  <div class="row">');
document.write('');
document.write('                    <!-- story -->');
document.write('                    <div class="col-md-4">');
document.write('                      <div class="story_box">');
document.write('                        <div class="story_img">');
document.write('                          <img src="https://catchup.cloud/portuguese/blog/images/blog13.jpg" alt="image">');
document.write('');
document.write('                        </div>');
document.write('                        <div class="story_text">');
document.write('                          <a href="https://catchup.cloud/portuguese/blog/blog_the_future_of_work_after_pandemic.html">');
document.write('                            <h3>O futuro do trabalho após a pandemia');
document.write('                            </h3>');
document.write('                          </a>');
document.write('                          <p>A pandemia do COVID-19 testemunhou uma transformação significativa em como trabalhamos, vivemos e pensamos sobre nosso futuro...</p>');
document.write('                          <a href="https://catchup.cloud/portuguese/blog/blog_the_future_of_work_after_pandemic.html">VER COMPLETO</a>');
document.write('                        </div>');
document.write('                      </div>');
document.write('                    </div>');
document.write('');

document.write('                    <!-- story -->');
document.write('                    <div class="col-md-4">');
document.write('                      <div class="story_box">');
document.write('                        <div class="story_img">');
document.write('                          <img src="https://catchup.cloud/portuguese/blog/images/blog14.jpg" alt="image">');
document.write('');
document.write('                        </div>');
document.write('                        <div class="story_text">');
document.write('                          <a href="https://catchup.cloud/portuguese/blog/blog_what_us_tech_talent_looks_for_in_remote_work.html">');
document.write('                            <h3>O que o talento tecnológico dos EUA procura no trabalho remoto?');
document.write('                            </h3>');
document.write('                          </a>');
document.write('                          <p>À medida que as empresas e organizações continuam a mudar para um ambiente de trabalho remoto...</p>');
document.write('                          <a href="https://catchup.cloud/portuguese/blog/blog_what_us_tech_talent_looks_for_in_remote_work.html">VER COMPLETO</a>');
document.write('                        </div>');
document.write('                      </div>');
document.write('                    </div>');

document.write('                    <!-- story -->');
document.write('                    <div class="col-md-4">');
document.write('                      <div class="story_box">');
document.write('                        <div class="story_img">');
document.write('                          <img src="https://catchup.cloud/portuguese/blog/images/blog15.jpg" alt="image">');
document.write('');
document.write('                        </div>');
document.write('                        <div class="story_text">');
document.write('                          <a href="https://catchup.cloud/portuguese/blog/blog_collaborative_communication__the_future_of_your_business.html">');
document.write('                            <h3>Comunicação colaborativa - o futuro do seu negócio');
document.write('                            </h3>');
document.write('                          </a>');
document.write('                          <p>O processo de compartilhamento de informações, feedback e ideias de forma a promover a cooperação...</p>');
document.write('                          <a href="https://catchup.cloud/portuguese/blog/blog_collaborative_communication__the_future_of_your_business.html">VER COMPLETO</a>');
document.write('                        </div>');
document.write('                      </div>');
document.write('                    </div>');
document.write('');
document.write('');
document.write('                  </div>');
document.write('                </div>');



document.write('                <div class="carousel-item">');
document.write('                  <div class="row">');
document.write('');
document.write('                    <!-- story -->');
document.write('                    <div class="col-md-4">');
document.write('                      <div class="story_box">');
document.write('                        <div class="story_img">');
document.write('                          <img src="https://catchup.cloud/portuguese/blog/images/blog16.jpg" alt="image">');
document.write('');
document.write('                        </div>');
document.write('                        <div class="story_text">');
document.write('                          <a href="https://catchup.cloud/portuguese/blog/blog_tips_to_being_an_accountable_team_member.html">');
document.write('                            <h3>Dicas para ser um membro responsável da equipe');
document.write('                            </h3>');
document.write('                          </a>');
document.write('                          <p>Ser um companheiro de equipe responsável é vital para toda equipe de sucesso. Implica aceitar a responsabilidade por seus deveres...</p>');
document.write('                          <a href="https://catchup.cloud/portuguese/blog/blog_tips_to_being_an_accountable_team_member.html">VER COMPLETO</a>');
document.write('                        </div>');
document.write('                      </div>');
document.write('                    </div>');
document.write('');

document.write('                    <!-- story -->');
document.write('                    <div class="col-md-4">');
document.write('                      <div class="story_box">');
document.write('                        <div class="story_img">');
document.write('                          <img src="https://catchup.cloud/portuguese/blog/images/blog17.jpg" alt="image">');
document.write('');
document.write('                        </div>');
document.write('                        <div class="story_text">');
document.write('                          <a href="https://catchup.cloud/portuguese/blog/blog_do_this_to_make_your_organization_successful.html">');
document.write('                            <h3>Faça isso para tornar sua organização bem-sucedida');
document.write('                            </h3>');
document.write('                          </a>');
document.write('                          <p>Cada organização tem seu conjunto único de desafios e perspectivas, mas certos princípios fundamentais podem ajudar a impulsionar...</p>');
document.write('                          <a href="https://catchup.cloud/portuguese/blog/blog_do_this_to_make_your_organization_successful.html">VER COMPLETO</a>');
document.write('                        </div>');
document.write('                      </div>');
document.write('                    </div>');

document.write('                    <!-- story -->');
document.write('                    <div class="col-md-4">');
document.write('                      <div class="story_box">');
document.write('                        <div class="story_img">');
document.write('                          <img src="https://catchup.cloud/portuguese/blog/images/blog18.jpg" alt="image">');
document.write('');
document.write('                        </div>');
document.write('                        <div class="story_text">');
document.write('                          <a href="https://catchup.cloud/portuguese/blog/blog_finding_the_best_project_management_software_using_the_okr_framework.html">');
document.write('                            <h3>Encontrar o melhor software de gerenciamento de projetos usando a estrutura OKR');
document.write('                            </h3>');
document.write('                          </a>');
document.write('                          <p>OKR (Objectives and Key Results) é um paradigma de definição de metas que ganhou...</p>');
document.write('                          <a href="https://catchup.cloud/portuguese/blog/blog_finding_the_best_project_management_software_using_the_okr_framework.html">VER COMPLETO</a>');
document.write('                        </div>');
document.write('                      </div>');
document.write('                    </div>');
document.write('');
document.write('                  </div>');
document.write('                </div>');


document.write('                <div class="carousel-item">');
document.write('                  <div class="row">');
document.write('');
document.write('                    <!-- story -->');
document.write('                    <div class="col-md-4">');
document.write('                      <div class="story_box">');
document.write('                        <div class="story_img">');
document.write('                          <img src="https://catchup.cloud/portuguese/blog/images/blog19.jpg" alt="image">');
document.write('');
document.write('                        </div>');
document.write('                        <div class="story_text">');
document.write('                          <a href="https://catchup.cloud/portuguese/blog/blog-ai-tools-like-chat-gpt-google-bard-are-about-to-revolutionize-project-management.html">');
document.write('                            <h3>Ferramentas de IA como ChatGPT e Google Bard estão prestes a revolucionar o gerenciamento de projetos');
document.write('                            </h3>');
document.write('                          </a>');
document.write('                          <p>A Inteligência Artificial (IA) já transformou indústrias em diversos setores ao automatizar a rotina...</p>');
document.write('                          <a href="https://catchup.cloud/portuguese/blog/blog-ai-tools-like-chat-gpt-google-bard-are-about-to-revolutionize-project-management.html">VER COMPLETO</a>');
document.write('                        </div>');
document.write('                      </div>');
document.write('                    </div>');
document.write('');

document.write('                    <!-- story -->');
document.write('                    <div class="col-md-4">');
document.write('                      <div class="story_box">');
document.write('                        <div class="story_img">');
document.write('                          <img src="https://catchup.cloud/portuguese/blog/images/blog20.jpg" alt="image">');
document.write('');
document.write('                        </div>');
document.write('                        <div class="story_text">');
document.write('                          <a href="https://catchup.cloud/portuguese/blog/blog-chat-gpt-vs.-your-job-vs.-project-management-software-solutions-is-it-wartime.html">');
document.write('                            <h3>ChatGPT vs. Seu Emprego vs. Soluções de Software de Gerenciamento de Projetos - É tempo de guerra?');
document.write('                            </h3>');
document.write('                          </a>');
document.write('                          <p>Com todas as tendências, coisas virais do ChatGPT on-line e pessoas dizendo que isso causará demissões em massa...</p>');
document.write('                          <a href="https://catchup.cloud/portuguese/blog/blog-chat-gpt-vs.-your-job-vs.-project-management-software-solutions-is-it-wartime.html">VER COMPLETO</a>');
document.write('                        </div>');
document.write('                      </div>');
document.write('                    </div>');

document.write('                    <!-- story -->');
document.write('                    <div class="col-md-4">');
document.write('                      <div class="story_box">');
document.write('                        <div class="story_img">');
document.write('                          <img src="https://catchup.cloud/portuguese/blog/images/diversity.jpg" alt="image">');
document.write('');
document.write('                        </div>');
document.write('                        <div class="story_text">');
document.write('                          <a href="https://catchup.cloud/portuguese/blog/blog-diversity-equity-and-inclusion.html">');
document.write('                            <h3>Diversité, équité et inclusion (DEI) - Importance et mise en œuvre (DEI - Diversity, Equity, and Inclusion)');
document.write('                            </h3>');
document.write('                          </a>');
document.write('                          <p>La diversité, l\'équité et l\'inclusion (DEI) sont des éléments essentiels du succès de toute organisation...</p>');
document.write('                          <a href="https://catchup.cloud/portuguese/blog/blog-diversity-equity-and-inclusion.html">VER COMPLETO</a>');
document.write('                        </div>');
document.write('                      </div>');
document.write('                    </div>');
document.write('');
document.write('                  </div>');
document.write('                </div>');

document.write('                <div class="carousel-item">');
document.write('                  <div class="row">');
document.write('');
document.write('                    <!-- story -->');
document.write('                    <div class="col-md-4">');
document.write('                      <div class="story_box">');
document.write('                        <div class="story_img">');
document.write('                          <img src="https://catchup.cloud/portuguese/blog/images/blog-tech.jpg" alt="image">');
document.write('');
document.write('                        </div>');
document.write('                        <div class="story_text">');
document.write('                          <a href="https://catchup.cloud/portuguese/blog/blog-leveraging-technology-for-effective-project-management.html">');
document.write('                            <h3>Aprovechamiento de la tecnología para una gestión eficaz de proyectos: estrategias clave y mejores prácticas');
document.write('                            </h3>');
document.write('                          </a>');
document.write('                          <p>Os avanços tecnológicos acelerados de hoje atingiram a maioria das esferas do trabalho e da vida...</p>');
document.write('                          <a href="https://catchup.cloud/portuguese/blog/blog-leveraging-technology-for-effective-project-management.html">VER COMPLETO</a>');
document.write('                        </div>');
document.write('                      </div>');
document.write('                    </div>');
document.write('');

document.write('                    <!-- story -->');
document.write('                    <div class="col-md-4">');
document.write('                      <div class="story_box">');
document.write('                        <div class="story_img">');
document.write('                          <img src="https://catchup.cloud/portuguese/blog/images/blog-ai.jpg" alt="image">');
document.write('');
document.write('                        </div>');
document.write('                        <div class="story_text">');
document.write('                          <a href="https://catchup.cloud/portuguese/blog/blog-impact-of-automation-and-artificial-intelligence-technologies-on-project-management-practices.html">');
document.write('                            <h3>Impacto das Tecnologias de Automação e Inteligência Artificial (IA) nas Práticas de Gerenciamento de Projetos');
document.write('                            </h3>');
document.write('                          </a>');
document.write('                          <p>Os rápidos avanços na tecnologia de automação e inteligência artificial...</p>');
document.write('                          <a href="https://catchup.cloud/portuguese/blog/blog-impact-of-automation-and-artificial-intelligence-technologies-on-project-management-practices.html">VER COMPLETO</a>');
document.write('                        </div>');
document.write('                      </div>');
document.write('                    </div>');

document.write('                    <!-- story -->');
document.write('                    <div class="col-md-4">');
document.write('                      <div class="story_box">');
document.write('                        <div class="story_img">');
document.write('                          <img src="https://catchup.cloud/portuguese/blog/images/blog-kanban.jpg" alt="image">');
document.write('');
document.write('                        </div>');
document.write('                        <div class="story_text">');
document.write('                          <a href="https://catchup.cloud/portuguese/blog/blog-kanban-board-vs-gantt-charts.html">');
document.write('                            <h3>Quadro Kanban contra Gráficos de Gantt');
document.write('                            </h3>');
document.write('                          </a>');
document.write('                          <p>Kanban Board e gráficos de Gantt são ferramentas populares que revolucionaram...</p>');
document.write('                          <a href="https://catchup.cloud/portuguese/blog/blog-kanban-board-vs-gantt-charts.html">VER COMPLETO</a>');
document.write('                        </div>');
document.write('                      </div>');
document.write('                    </div>');
document.write('');
document.write('                  </div>');
document.write('                </div>');

document.write('                <div class="carousel-item">');
document.write('                  <div class="row">');
document.write('');
document.write('                    <!-- story -->');
document.write('                    <div class="col-md-4">');
document.write('                      <div class="story_box">');
document.write('                        <div class="story_img">');
document.write('                          <img src="https://catchup.cloud/portuguese/blog/images/blog-effective.jpg" alt="image">');
document.write('');
document.write('                        </div>');
document.write('                        <div class="story_text">');
document.write('                          <a href="https://catchup.cloud/portuguese/blog/blog-the-evolution-of-project-management-tools.html">');
document.write('                            <h3>A evolução das ferramentas de gerenciamento de projetos: fortalecendo o sucesso por meio de avanços tecnológicos');
document.write('                            </h3>');
document.write('                          </a>');
document.write('                          <p>O gerenciamento eficaz de projetos sempre foi essencial para que as organizações...</p>');
document.write('                          <a href="https://catchup.cloud/portuguese/blog/blog-the-evolution-of-project-management-tools.html">VER COMPLETO</a>');
document.write('                        </div>');
document.write('                      </div>');
document.write('                    </div>');
document.write('');

document.write('                    <!-- story -->');
document.write('                    <div class="col-md-4">');
document.write('                      <div class="story_box">');
document.write('                        <div class="story_img">');
document.write('                          <img src="https://catchup.cloud/portuguese/blog/images/blog22.jpg" alt="image">');
document.write('');
document.write('                        </div>');
document.write('                        <div class="story_text">');
document.write('                          <a href="https://catchup.cloud/portuguese/blog/blog-data-breach-prevention-how-iso-27001-2022-keeps-your-data-safe.html">');
document.write('                            <h3>Prevenção de violação de dados: como a ISO 27001:2022 mantém seus dados seguros?');
document.write('                            </h3>');
document.write('                          </a>');
document.write('                          <p>O ativo mais significativo do mundo digital de hoje são os dados, por isso sua proteção contra possíveis violações...</p>');
document.write('                          <a href="https://catchup.cloud/portuguese/blog/blog-data-breach-prevention-how-iso-27001-2022-keeps-your-data-safe.html">VER COMPLETO</a>');
document.write('                        </div>');
document.write('                      </div>');
document.write('                    </div>');

// document.write('                    <!-- story -->');
// document.write('                    <div class="col-md-4">');
// document.write('                      <div class="story_box">');
// document.write('                        <div class="story_img">');
// document.write('                          <img src="https://catchup.cloud/portuguese/blog/images/diversity.jpg" alt="image">');
// document.write('');
// document.write('                        </div>');
// document.write('                        <div class="story_text">');
// document.write('                          <a href="https://catchup.cloud/portuguese/blog/blog-diversity-equity-and-inclusion.html">');
// document.write('                            <h3>Diversité, équité et inclusion (DEI) - Importance et mise en œuvre (DEI - Diversity, Equity, and Inclusion)');
// document.write('                            </h3>');
// document.write('                          </a>');
// document.write('                          <p>La diversité, l\'équité et l\'inclusion (DEI) sont des éléments essentiels du succès de toute organisation...</p>');
// document.write('                          <a href="https://catchup.cloud/portuguese/blog/blog-diversity-equity-and-inclusion.html">VER COMPLETO</a>');
// document.write('                        </div>');
// document.write('                      </div>');
// document.write('                    </div>');
document.write('');
document.write('                  </div>');
document.write('                </div>');


document.write('');
document.write('');
document.write('');
document.write('');
document.write('              </div>');
document.write('            </div>');
document.write('          </div>');
document.write('        </div>');
document.write('      </div>');
document.write('    </section>');
