document.write("<!-- Header Start -->");
document.write("    <header>");
document.write("      <!-- container start -->");
document.write("      <div class=\"container\">");
document.write("      	<!-- navigation bar -->");
document.write("        <nav class=\"navbar navbar-expand-lg\">");
document.write("          <a class=\"navbar-brand\" href=\"http:\/\/catchup.cloud\/french\/index.html\">");
document.write("            <img src=\"http://catchup.cloud/images/logo.png\" alt=\"image\" >");
document.write("          </a>");
document.write("          <button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\" data-target=\"#navbarSupportedContent\"");
document.write("            aria-controls=\"navbarSupportedContent\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">");
document.write("            <span class=\"navbar-toggler-icon\">");
document.write("              <!-- <i class=\"icofont-navigation-menu ico_menu\"></i> -->");
document.write("              <div class=\"toggle-wrap\">");
document.write("                <span class=\"toggle-bar\"></span>");
document.write("              </div>");
document.write("            </span>");
document.write("          </button>");
document.write("");
document.write("          <div class=\"collapse navbar-collapse\" id=\"navbarSupportedContent\">");
document.write("            <ul class=\"navbar-nav ml-auto\">");
document.write("              <li class=\"nav-item active\">");
document.write("                <a class=\"nav-link\" href=\"http://catchup.cloud/french/index.html\">Maison</a>");
document.write("              </li>");
document.write("              <li class=\"nav-item\">");
document.write("                <a class=\"nav-link\" href=\"http://catchup.cloud/french/features.html\">Fonctionnalités</a>");
document.write("              </li>");

document.write("              <li class=\"nav-item\">");
document.write("                <a class=\"nav-link\" href=\"http://catchup.cloud/french/pricing.html\">Tarification</a>");
document.write("              </li>");

document.write("              <li class=\"nav-item\">");
document.write("                <a class=\"nav-link\" href=\"http://catchup.cloud/french/whycatchup.html\">Pourquoi CatchUp</a>");
document.write("              </li>");
document.write("              <!-- secondery menu start -->");
document.write("              <li class=\"nav-item has_dropdown\">");
document.write("                <a class=\"nav-link\" href=\"#\">Cas d'usage</a>");
document.write("                <span class=\"drp_btn\"><i class=\"icofont-rounded-down\"></i></span>");
document.write("                <div class=\"sub_menu\">");
document.write("                  <ul>");
document.write("                    <li><a href=\"http://catchup.cloud/french/usecases.html\">Industrie du service</a></li>");
document.write("                    <li><a href=\"http://catchup.cloud/french/usecases.html#it_companies\">Entreprises informatiques</a></li>");
document.write("                    <li><a href=\"http://catchup.cloud/french/usecases.html#digital_agencies\">Agences numériques</a></li>");
document.write("                    <li><a href=\"http://catchup.cloud/french/usecases.html#marketing_firms\">Entreprises de commercialisation</a></li>");
document.write("                    <li><a href=\"http://catchup.cloud/french/usecases.html#law_firms\">Cabinets d'avocats</a></li>                    ");
document.write("                  </ul>");
document.write("                </div>");
document.write("              </li>");
document.write("              <!-- secondery menu end -->");
document.write("");

document.write("              ");
document.write("              <!-- secondery menu start -->");
document.write("              <li class=\"nav-item has_dropdown\">");
document.write("                <a class=\"nav-link\" href=\"#\">Ressources</a>");
document.write("                <span class=\"drp_btn\"><i class=\"icofont-rounded-down\"></i></span>");
document.write("                <div class=\"sub_menu\">");
document.write("                  <ul>");
document.write("                    <li><a href=\"http://catchup.cloud/french/blog/index.html\">Blog</a></li>");
document.write("                    <li><a href=\"http://catchup.cloud/french/docs/index.html\">Documentation</a></li>");
document.write("                    <li><a href=\"http://catchup.cloud/french/integrations.html\">Intégrations</a></li>");
document.write("                    <li><a href=\"http://catchup.cloud/french/faq.html\">Foire aux questions</a></li>");
document.write("                    <li><a href=\"http://catchup.cloud/french/contact.html\">Contact</a></li>");

document.write("                  </ul>");
document.write("                </div>");
document.write("              </li>");
document.write("              <!-- secondery menu end -->");
document.write("              ");
document.write("              ");
document.write("              <li class=\"nav-item\">");
document.write("                <a class=\"nav-link\" href=\"https://dashboard.catchup.cloud\/accounts\/login\/?lang=fr\">Connexion</a>");
document.write("              </li>");
document.write("              <li class=\"nav-item\">");
document.write("                <a class=\"nav-link dark_btn\" href=\"https://dashboard.catchup.cloud\/accounts\/signup\/?lang=fr\">S'INSCRIRE</a>");
document.write("              </li>");
document.write("            </ul>");
document.write("          </div>");
document.write("        </nav>");
document.write("        <!-- navigation end -->");
document.write("      </div>");
document.write("      <!-- container end -->");
document.write("    </header>");
