_linkedin_partner_id = "4480052";
window._linkedin_data_partner_ids = window._linkedin_data_partner_ids || [];
window._linkedin_data_partner_ids.push(_linkedin_partner_id);

(function(l) {
if (!l){window.lintrk = function(a,b){window.lintrk.q.push([a,b])};
window.lintrk.q=[]}
var s = document.getElementsByTagName("script")[0];
var b = document.createElement("script");
b.type = "text/javascript";b.async = true;
b.src = "https://snap.licdn.com/li.lms-analytics/insight.min.js";
s.parentNode.insertBefore(b, s);})(window.lintrk);


document.write("<noscript>");
document.write("<img height=\"1\" width=\"1\" style=\"display:none;\" alt=\"\" src=\"https://px.ads.linkedin.com/collect/?pid=4480052&fmt=gif\" />");
document.write("</noscript>");

document.write("<!-- Footer-Section start -->");
document.write("    <footer>");
document.write("        <div class=\"top_footer\" id=\"contact\">");
document.write("            <!-- container start -->");
document.write("            <div class=\"container\">");
document.write("              <!-- row start -->");
document.write("              <div class=\"row\">");
document.write("                  <!-- shape animation  -->");
document.write("                  <span class=\"banner_shape1\"> <img src=\"http://catchup.cloud/images/whales4.png\" alt=\"image\" > </span>");
//document.write("                  <span class=\"banner_shape2\"> <img src=\"http://catchup.cloud/images/whales3.png\" alt=\"image\" > </span>");
document.write("                  <span class=\"banner_shape3\"> <img src=\"http://catchup.cloud/images/whales5.png\" alt=\"image\" > </span>");
document.write("");
document.write("                  <!-- footer link 1 -->");
document.write("                  <div class=\"col-lg-4 col-md-6 col-12\">");
document.write("                      <div class=\"abt_side\">");
document.write("                        <div class=\"logo\"> <img src=\"http://catchup.cloud/images/logo.png\" alt=\"image\" ></div>");
document.write("                                              ");
document.write("                          <p>CatchUp es un entorno de próxima generación de colaboración en tiempo real, gestión de proyectos, programación de tareas, planificación y ejecución, y optimización de recursos para organizaciones.</li>");
document.write("                          </p>");
document.write("                        <ul class=\"social_media\">");
document.write("                            <li><a href=\"https://www.linkedin.com/company/catchup-cloud\" target=\"_blank\"><i class=\"icofont-linkedin\"></i></a></li>");
document.write("                            <li><a href=\"https://www.facebook.com/catchupcloud\" target=\"_blank\"><i class=\"icofont-facebook\"></i></a></li>");
document.write("                            <li><a href=\"https://twitter.com/catchupcloud\" target=\"_blank\"><i class=\"icofont-twitter\"></i></a></li>");
document.write("                            <li><a href=\"https://www.instagram.com/catchupcloud\" target=\"_blank\"><i class=\"icofont-instagram\"></i></a></li>");
document.write("                            <li><a href=\"https://medium.com/@contact_73890\" target=\"_blank\"><i class=\"fa fa-medium\" aria-hidden=\"true\"></i></a></li>");
document.write("                        </ul>");

document.write("                        <div class=\"logo\" style=\"margin:0;padding:0;\"> <img src=\"../images/iso.png\" alt=\"CatchUp\" ></div>");

document.write("                      </div>");
document.write("                  </div>");
document.write("");
document.write("                  <!-- footer link 2 -->");
document.write("                  <div class=\"col-lg-2 col-md-6 col-12\">");
document.write("                      <div class=\"links\">");
document.write("                        <h3>Enlaces útiles</h3>");
document.write("                          <ul>");
document.write("                            <li><a href=\"http://catchup.cloud/spanish/index.html\">Hogar</a></li>");
document.write("                            <li><a href=\"http://catchup.cloud/spanish/about.html\">Sobre nosotros</a></li>                            ");
document.write("                            <li><a href=\"https://catchup.cloud/spanish/features.html\">Características</a></li>   ");
document.write("                            <li><a href=\"https://dashboard.catchup.cloud/\">Panel</a></li>                            ");
document.write("                            <li><a href=\"http://catchup.cloud/spanish/contact.html\">Contáctenos</a></li>");
document.write("                          </ul>");
document.write("                      </div>");
document.write("                  </div>");
document.write("");
document.write("                  <!-- footer link 3 -->");
document.write("                  <div class=\"col-lg-2 col-md-6 col-12\">");
document.write("                    <div class=\"links\">");
document.write("                      <h3>Recursos</h3>");
document.write("                        <ul>");
document.write("                          <li><a href=\"http://catchup.cloud/spanish/blog/index.html\">Blog</a></li>");
document.write("                          <li><a href=\"http://catchup.cloud/spanish/docs/index.html\">Documentación</a></li>                          ");
document.write("                          <li><a href=\"http://catchup.cloud/spanish/faq.html\">Preguntas frecuentes</a></li>");
document.write("                          <li><a href=\"http://catchup.cloud/spanish/terms.html\">Términos y condiciones</a></li>");
document.write("                          <li><a href=\"http://catchup.cloud/spanish/privacy.html\">Política de privacidad</a></li>");
document.write("                        </ul>");
document.write("                    </div>");
document.write("                  </div>");
document.write("");
document.write("                  <!-- footer link 2 -->");
document.write("                  <div class=\"col-lg-2 col-md-6 col-12\">");
document.write("                      <div class=\"links\">");
document.write("                        <h3>Comparaciones</h3>");
document.write("                          <ul>");
document.write("                            <li><a href=\"http://catchup.cloud/spanish/asana-alternative.html\">vs Asana</a></li>");
document.write("                            <li><a href=\"http://catchup.cloud/spanish/basecamp-alternative.html\">vs Basecamp</a></li>");
document.write("                            <li><a href=\"http://catchup.cloud/spanish/clickup-alternative.html\">vs ClickUp</a></li>");
document.write("                            <li><a href=\"http://catchup.cloud/spanish/monday-alternative.html\">vs Monday.com</a></li>");
document.write("                            <li><a href=\"http://catchup.cloud/spanish/trello-alternative.html\">vs Trello</a></li>");
document.write("                            <li><a href=\"http://catchup.cloud/spanish/nifty-alternative.html\">vs Nifty</a></li>");

document.write("                          </ul>");
document.write("                      </div>");
document.write("                  </div>");
document.write("");
document.write("                  <!-- footer link 4 -->");
document.write("                  <div class=\"col-lg-2 col-md-6 col-12\">");
document.write("                    <div class=\"try_out\">");
document.write("                        <h3>Obtener la aplicación</h3>");
document.write("                        <ul class=\"app_btn\">");
document.write("                          <li>");
document.write("                            <a href=\"https://apps.apple.com/in/app/catchup-work/id6444959662\" target=\"_blank\">");
document.write("                              <img src=\"http://catchup.cloud/images/appstore_blue.png\" alt=\"image\" >");
document.write("                            </a>");
document.write("                          </li>");
document.write("                          <li>");
document.write("                            <a href=\"https://play.google.com/store/apps/details?id=com.cloud.catchup\" target=\"_blank\">");
document.write("                              <img src=\"http://catchup.cloud/images/googleplay_blue.png\" alt=\"image\" >");
document.write("                            </a>");
document.write("                          </li>");
document.write("                        </ul>");
document.write("                    </div>");
document.write("                        <div class=\"logo\" style=\"margin-top:20px;padding:0;\"> <img src=\"../images/r.png\" alt=\"CatchUp\" ></div>");
document.write("                        <a href=\"https://www.techtimes.com/articles/291880/20230524/top-5-project-collaboration-tools-2023.htm\" target=\"_blank\"><div class=\"logo\" style=\"margin:0px;padding:0;width:120px;\"> <img src=\"../images/techtimes.png\" alt=\"CatchUp\"></div></a>");
document.write("                  </div>");
document.write("                  </div>");
document.write("              </div>");
document.write("              <!-- row end -->");
document.write("          </div>");
document.write("          <!-- container end -->");
document.write("        </div>");
document.write("");
document.write("        <!-- last footer -->");
document.write("        <div class=\"bottom_footer\">");
document.write("          <!-- container start -->");
document.write("            <div class=\"container\">");
document.write("              <!-- row start -->");
document.write("              <div class=\"row\">");
document.write("                <div class=\"col-md-6\">");
document.write("                    <p>© CatchUp. Reservados todos los derechos.</p>");
document.write("                </div>");
document.write("                <div class=\"col-md-6\">");
document.write("                    <p style=\"text-align:right\"><a href=\"https://catchup.cloud\">🇺🇸 English</a> | <a href=\"https://catchup.cloud/spanish/\">🇪🇸 Español</a> | <a href=\"https://catchup.cloud/french/\">🇫🇷 Français</a> | <a href=\"https://catchup.cloud/portuguese/\">🇵🇹 Português</a> | <a href=\"https://catchup.cloud/german/\">🇩🇪 Deutsch</a></p>");
document.write("                </div>");
document.write("                ");
document.write("            </div>");
document.write("            <!-- row end -->");
document.write("            </div>");
document.write("            <!-- container end -->");
document.write("        </div>");
document.write("");
document.write("        <!-- go top button -->");
document.write("        <div class=\"go_top\">");
document.write("            <span><img src=\"http://catchup.cloud/images/go_top.png\" alt=\"image\" ></span>");
document.write("        </div>");
document.write("    </footer>");