document.write("<!-- Header Start -->");
document.write("    <header>");
document.write("      <!-- container start -->");
document.write("      <div class=\"container\">");
document.write("      	<!-- navigation bar -->");
document.write("        <nav class=\"navbar navbar-expand-lg\">");
document.write("          <a class=\"navbar-brand\" href=\"http:\/\/catchup.cloud\/spanish\/index.html\">");
document.write("            <img src=\"../images/logo.png\" alt=\"image\" >");
document.write("          </a>");
document.write("          <button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\" data-target=\"#navbarSupportedContent\"");
document.write("            aria-controls=\"navbarSupportedContent\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">");
document.write("            <span class=\"navbar-toggler-icon\">");
document.write("              <!-- <i class=\"icofont-navigation-menu ico_menu\"></i> -->");
document.write("              <div class=\"toggle-wrap\">");
document.write("                <span class=\"toggle-bar\"></span>");
document.write("              </div>");
document.write("            </span>");
document.write("          </button>");
document.write("");
document.write("          <div class=\"collapse navbar-collapse\" id=\"navbarSupportedContent\">");
document.write("            <ul class=\"navbar-nav ml-auto\">");
document.write("              <li class=\"nav-item active\">");
document.write("                <a class=\"nav-link\" href=\"http://catchup.cloud/spanish/index.html\">Hogar</a>");
document.write("              </li>");
document.write("              <li class=\"nav-item\">");
document.write("                <a class=\"nav-link\" href=\"http://catchup.cloud/spanish/features.html\">Características</a>");
document.write("              </li>");

document.write("              <li class=\"nav-item\">");
document.write("                <a class=\"nav-link\" href=\"http://catchup.cloud/spanish/pricing.html\">Precios</a>");
document.write("              </li>");

document.write("              <li class=\"nav-item\">");
document.write("                <a class=\"nav-link\" href=\"http://catchup.cloud/spanish/whycatchup.html\">¿Por qué CatchUp?</a>");
document.write("              </li>");
document.write("              <!-- secondery menu start -->");
document.write("              <li class=\"nav-item has_dropdown\">");
document.write("                <a class=\"nav-link\" href=\"#\">Casos de uso</a>");
document.write("                <span class=\"drp_btn\"><i class=\"icofont-rounded-down\"></i></span>");
document.write("                <div class=\"sub_menu\">");
document.write("                  <ul>");
document.write("                    <li><a href=\"http://catchup.cloud/spanish/usecases.html\">Servicio Industrial</a></li>");
document.write("                    <li><a href=\"http://catchup.cloud/spanish/usecases.html#it_companies\">Empresas de TI</a></li>");
document.write("                    <li><a href=\"http://catchup.cloud/spanish/usecases.html#digital_agencies\">Agencias Digitales</a></li>");
document.write("                    <li><a href=\"http://catchup.cloud/spanish/usecases.html#marketing_firms\">Empresas de marketing</a></li>");
document.write("                    <li><a href=\"http://catchup.cloud/spanish/usecases.html#law_firms\">Bufetes de abogados</a></li>                    ");
document.write("                  </ul>");
document.write("                </div>");
document.write("              </li>");
document.write("              <!-- secondery menu end -->");
document.write("");

document.write("              ");
document.write("              <!-- secondery menu start -->");
document.write("              <li class=\"nav-item has_dropdown\">");
document.write("                <a class=\"nav-link\" href=\"#\">Recursos</a>");
document.write("                <span class=\"drp_btn\"><i class=\"icofont-rounded-down\"></i></span>");
document.write("                <div class=\"sub_menu\">");
document.write("                  <ul>");
document.write("                    <li><a href=\"http://catchup.cloud/spanish/blog/index.html\">Blog</a></li>");
document.write("                    <li><a href=\"http://catchup.cloud/spanish/docs/index.html\">Documentación</a></li>");
document.write("                    <li><a href=\"http://catchup.cloud/spanish/integrations.html\">Integraciones</a></li>");
document.write("                    <li><a href=\"http://catchup.cloud/spanish/faq.html\">Preguntas frecuentes</a></li>");
document.write("                    <li><a href=\"http://catchup.cloud/spanish/contact.html\">Contacto</a></li>");

document.write("                  </ul>");
document.write("                </div>");
document.write("              </li>");
document.write("              <!-- secondery menu end -->");
document.write("              ");
document.write("              ");
document.write("              <li class=\"nav-item\">");
document.write("                <a class=\"nav-link\" href=\"https://dashboard.catchup.cloud\">Acceso</a>");
document.write("              </li>");
document.write("              <li class=\"nav-item\">");
document.write("                <a class=\"nav-link dark_btn\" href=\"https://dashboard.catchup.cloud\/accounts\/signup\/\">INSCRIBIRSE</a>");
document.write("              </li>");
document.write("            </ul>");
document.write("          </div>");
document.write("        </nav>");
document.write("        <!-- navigation end -->");
document.write("      </div>");
document.write("      <!-- container end -->");
document.write("    </header>");
