document.write('<section class="row_am latest_story blog_list_story">');
document.write('      <div class="container">');
document.write('        <div class="row">');
document.write('          <div class="col-6">');
document.write('            <h2 class="mb-3">Latest from Blog</h2>');
document.write('          </div>');
document.write('          <div class="col-6 text-right">');
document.write('            <a class="btn btn-primary mb-3 mr-1" href="#carouselExampleIndicators2" role="button" data-slide="prev"');
document.write('              style="background-color: #32236F; border-color: #32236F;">');
document.write('              <i class="fa fa-arrow-left"></i>');
document.write('            </a>');
document.write('            <a class="btn btn-primary mb-3 " href="#carouselExampleIndicators2" role="button" data-slide="next"');
document.write('              style="background-color: #32236F; border-color: #32236F;">');
document.write('              <i class="fa fa-arrow-right"></i>');
document.write('            </a>');
document.write('          </div>');
document.write('          <div class="col-12">');
document.write('            <div id="carouselExampleIndicators2" class="carousel slide" data-ride="carousel">');
document.write('');
document.write('              <div class="carousel-inner">');
document.write('');
document.write('');
document.write('                <div class="carousel-item active">');
document.write('                  <div class="row">');
document.write('');
document.write('                    <!-- story -->');
document.write('                    <div class="col-md-4">');
document.write('                      <div class="story_box">');
document.write('                        <div class="story_img">');
document.write('                          <img src="https://catchup.cloud/blog/images/blog1.jpg" alt="image">');
document.write('');
document.write('                        </div>');
document.write('                        <div class="story_text">');
document.write('                          <a href="https://catchup.cloud/blog/blog_how_project_management_tool_can_enhance_office_productivity.html">');
document.write('                            <h3>How a project management tool can enhance your office productivity?');
document.write('                            </h3>');
document.write('                          </a>');
document.write('                          <p>In today\'s business world, effective project management is essential to success...</p>');
document.write('                          <a href="https://catchup.cloud/blog/blog_how_project_management_tool_can_enhance_office_productivity.html">READ MORE</a>');
document.write('                        </div>');
document.write('                      </div>');
document.write('                    </div>');
document.write('');
document.write('                    <!-- story -->');
document.write('                    <div class="col-md-4">');
document.write('                      <div class="story_box">');
document.write('                        <div class="story_img">');
document.write('                          <img src="https://catchup.cloud/blog/images/blog2.jpg" alt="image">');
document.write('');
document.write('                        </div>');
document.write('                        <div class="story_text">');
document.write('                          <a href="https://catchup.cloud/blog/blog_what_features_to_look_for_in_project_management_tool.html">');
document.write('                            <h3>What features to look for in a project management tool?');
document.write('                            </h3>');
document.write('                          </a>');
document.write('                          <p>To ensure maximum efficiency, certain must-have features should be considered when');
document.write('                            selecting a project management tool...');
document.write('                          </p>');
document.write('                          <a href="https://catchup.cloud/blog/blog_what_features_to_look_for_in_project_management_tool.html">READ MORE</a>');
document.write('                        </div>');
document.write('                      </div>');
document.write('                    </div>');
document.write('');
document.write('                    <!-- story -->');
document.write('                    <div class="col-md-4">');
document.write('                      <div class="story_box">');
document.write('                        <div class="story_img">');
document.write('                          <img src="https://catchup.cloud/blog/images/blog3.jpg" alt="image">');
document.write('');
document.write('                        </div>');
document.write('                        <div class="story_text">');
document.write('                          <a href="https://catchup.cloud/blog/blog_why_you_should_use_a_project_management_tool.html">');
document.write('                            <h3>Why should you use a project management tool?');
document.write('                            </h3>');
document.write('                          </a>');
document.write('                          <p>A project management system is a valuable tool for any organization. It can help you');
document.write('                            streamline your workflow...');
document.write('                          </p>');
document.write('                          <a href="https://catchup.cloud/blog/blog_why_you_should_use_a_project_management_tool.html">READ MORE</a>');
document.write('                        </div>');
document.write('                      </div>');
document.write('                    </div>');
document.write('');
document.write('');
document.write('                  </div>');
document.write('                </div>');
document.write('');
document.write('                <div class="carousel-item">');
document.write('                  <div class="row">');
document.write('');
document.write('                    <!-- story -->');
document.write('                    <div class="col-md-4">');
document.write('                      <div class="story_box">');
document.write('                        <div class="story_img">');
document.write('                          <img src="https://catchup.cloud/blog/images/blog6.jpg" alt="image">');
document.write('');
document.write('                        </div>');
document.write('                        <div class="story_text">');
document.write('                          <a href="https://catchup.cloud/blog/blog_how_kanban_helps_teams_be_productive.html">');
document.write('                            <h3>How Kanban helps teams be productive?');
document.write('                            </h3>');
document.write('                          </a>');
document.write('                          <p>Kanban is a methodology for planning, scheduling and enhancing work across systems...</p>');
document.write('                          <a href="https://catchup.cloud/blog/blog_how_kanban_helps_teams_be_productive.html">READ MORE</a>');
document.write('                        </div>');
document.write('                      </div>');
document.write('                    </div>');
document.write('');
document.write('                    <!-- story -->');
document.write('                    <div class="col-md-4">');
document.write('                      <div class="story_box">');
document.write('                        <div class="story_img">');
document.write('                          <img src="https://catchup.cloud/blog/images/blog5.jpg" alt="image">');
document.write('');
document.write('                        </div>');
document.write('                        <div class="story_text">');
document.write('                          <a href="https://catchup.cloud/blog/blog_what_is_a_project_management_software.html">');
document.write('                            <h3>What is a project management software and why do you need it?');
document.write('                            </h3>');
document.write('                          </a>');
document.write('                          <p>A project management software is a tool that helps organizations plan...</p>');
document.write('                          <a href="https://catchup.cloud/blog/blog_what_is_a_project_management_software.html">READ MORE</a>');
document.write('                        </div>');
document.write('                      </div>');
document.write('                    </div>');
document.write('');
document.write('                    <!-- story -->');
document.write('                    <div class="col-md-4">');
document.write('                      <div class="story_box">');
document.write('                        <div class="story_img">');
document.write('                          <img src="https://catchup.cloud/blog/images/blog4.jpg" alt="image">');
document.write('');
document.write('                        </div>');
document.write('                        <div class="story_text">');
document.write('                          <a href="https://catchup.cloud/blog/blog_your_guide_to_effective_project_management.html">');
document.write('                            <h3>Your guide to effective project management');
document.write('                            </h3>');
document.write('                          </a>');
document.write('                          <p>A project is a collection of tasks that must be completed in a specific time frame...</p>');
document.write('                          <a href="https://catchup.cloud/blog/blog_your_guide_to_effective_project_management.html">READ MORE</a>');
document.write('                        </div>');
document.write('                      </div>');
document.write('                    </div>');
document.write('');
document.write('');
document.write('                  </div>');
document.write('                </div>');
document.write('');
document.write('                <div class="carousel-item">');
document.write('                  <div class="row">');
document.write('');
document.write('                    <!-- story -->');
document.write('                    <div class="col-md-4">');
document.write('                      <div class="story_box">');
document.write('                        <div class="story_img">');
document.write('                          <img src="https://catchup.cloud/blog/images/blog9.jpg" alt="image">');
document.write('');
document.write('                        </div>');
document.write('                        <div class="story_text">');
document.write('                          <a href="https://catchup.cloud/blog/blog_top_5_tips_for_effective_project_management.html">');
document.write('                            <h3>Top 5 Tips for effective project management');
document.write('                            </h3>');
document.write('                          </a>');
document.write('                          <p>Getting quality services and products delivered within a given time limit and budget is the');
document.write('                            need of any business...</p>');
document.write('                          <a href="https://catchup.cloud/blog/blog_top_5_tips_for_effective_project_management.html">READ MORE</a>');
document.write('                        </div>');
document.write('                      </div>');
document.write('                    </div>');
document.write('');
document.write('                    <!-- story -->');
document.write('                    <div class="col-md-4">');
document.write('                      <div class="story_box">');
document.write('                        <div class="story_img">');
document.write('                          <img src="https://catchup.cloud/blog/images/blog8.jpg" alt="image">');
document.write('');
document.write('                        </div>');
document.write('                        <div class="story_text">');
document.write('                          <a href="https://catchup.cloud/blog/blog_top_5_best_practices_for_remote_work_management.html">');
document.write('                            <h3>Top 5 best practices for remote work management');
document.write('                            </h3>');
document.write('                          </a>');
document.write('                          <p>Remote work has become a norm in the current world, and it\'s essential for organizations...');
document.write('                          </p>');
document.write('                          <a href="https://catchup.cloud/blog/blog_top_5_best_practices_for_remote_work_management.html">READ MORE</a>');
document.write('                        </div>');
document.write('                      </div>');
document.write('                    </div>');
document.write('');
document.write('                    <!-- story -->');
document.write('                    <div class="col-md-4">');
document.write('                      <div class="story_box">');
document.write('                        <div class="story_img">');
document.write('                          <img src="https://catchup.cloud/blog/images/blog7.jpg" alt="image">');
document.write('');
document.write('                        </div>');
document.write('                        <div class="story_text">');
document.write('                          <a href="https://catchup.cloud/blog/blog_top_10_remote_work_management_mistakes_and_how_to_avoid_them.html">');
document.write('                            <h3>Top 10 remote work management mistakes and how to avoid them');
document.write('                            </h3>');
document.write('                          </a>');
document.write('                          <p>As remote work becomes more popular, a growing number of...</p>');
document.write('                          <a href="https://catchup.cloud/blog/blog_top_10_remote_work_management_mistakes_and_how_to_avoid_them.html">READ MORE</a>');
document.write('                        </div>');
document.write('                      </div>');
document.write('                    </div>');
document.write('');
document.write('');
document.write('                  </div>');
document.write('                </div>');
document.write('');
document.write('                <div class="carousel-item">');
document.write('                  <div class="row">');
document.write('');
document.write('                    <!-- story -->');
document.write('                    <div class="col-md-4">');
document.write('                      <div class="story_box">');
document.write('                        <div class="story_img">');
document.write('                          <img src="https://catchup.cloud/blog/images/blog12.jpg" alt="image">');
document.write('');
document.write('                        </div>');
document.write('                        <div class="story_text">');
document.write('                          <a href="https://catchup.cloud/blog/blog_understanding_cobra_typology_for_brand_growth.html">');
document.write('                            <h3>Understanding COBRA (customers\' online brand-related behaviors) Typology for Brand');
document.write('                              Growth');
document.write('                            </h3>');
document.write('                          </a>');
document.write('                          <p>Businesses active in the digital space...</p>');
document.write('                          <a href="https://catchup.cloud/blog/blog_understanding_cobra_typology_for_brand_growth.html">READ MORE</a>');
document.write('                        </div>');
document.write('                      </div>');
document.write('                    </div>');
document.write('');
document.write('');
document.write('                    <!-- story -->');
document.write('                    <div class="col-md-4">');
document.write('                      <div class="story_box">');
document.write('                        <div class="story_img">');
document.write('                          <img src="https://catchup.cloud/blog/images/blog11.jpg" alt="image">');
document.write('');
document.write('                        </div>');
document.write('                        <div class="story_text">');
document.write('                          <a');
document.write('                            href="https://catchup.cloud/blog/blog_how_a_good_project_management_tool_helps_manage_transformation_expenditures.html">');
document.write('                            <h3>How a good project management tool helps manage transformation expenditures');
document.write('                            </h3>');
document.write('                          </a>');
document.write('                          <p>Transformation expenditures are...</p>');
document.write('                          <a');
document.write('                            href="https://catchup.cloud/blog/blog_how_a_good_project_management_tool_helps_manage_transformation_expenditures.html">READ');
document.write('                            MORE</a>');
document.write('                        </div>');
document.write('                      </div>');
document.write('                    </div>');
document.write('');
document.write('                    <!-- story -->');
document.write('                    <div class="col-md-4">');
document.write('                      <div class="story_box">');
document.write('                        <div class="story_img">');
document.write('                          <img src="https://catchup.cloud/blog/images/blog10.jpg" alt="image">');
document.write('');
document.write('                        </div>');
document.write('                        <div class="story_text">');
document.write('                          <a href="https://catchup.cloud/blog/blog_why_leading_companies_are_prioritizing_digital_transformation.html">');
document.write('                            <h3>Why leading companies are prioritizing digital transformation?');
document.write('                            </h3>');
document.write('                          </a>');
document.write('                          <p>Digital transformation is increasingly becoming a priority for businesses...</p>');
document.write('                          <a href="https://catchup.cloud/blog/blog_why_leading_companies_are_prioritizing_digital_transformation.html">READ');
document.write('                            MORE</a>');
document.write('                        </div>');
document.write('                      </div>');
document.write('                    </div>');
document.write('');
document.write('');
document.write('                  </div>');
document.write('                </div>');
document.write('');
document.write('                <div class="carousel-item">');
document.write('                  <div class="row">');
document.write('');
document.write('                    <!-- story -->');
document.write('                    <div class="col-md-4">');
document.write('                      <div class="story_box">');
document.write('                        <div class="story_img">');
document.write('                          <img src="https://catchup.cloud/blog/images/blog13.jpg" alt="image">');
document.write('');
document.write('                        </div>');
document.write('                        <div class="story_text">');
document.write('                          <a href="https://catchup.cloud/blog/blog_the_future_of_work_after_pandemic.html">');
document.write('                            <h3>The future of work after pandemic');
document.write('                            </h3>');
document.write('                          </a>');
document.write('                          <p>The COVID-19 pandemic witnessed a significant transformation in how we work, live, and');
document.write('                            think about our future...</p>');
document.write('                          <a href="https://catchup.cloud/blog/blog_the_future_of_work_after_pandemic.html">READ MORE</a>');
document.write('                        </div>');
document.write('                      </div>');
document.write('                    </div>');
document.write('');

document.write('                    <!-- story -->');
document.write('                    <div class="col-md-4">');
document.write('                      <div class="story_box">');
document.write('                        <div class="story_img">');
document.write('                          <img src="https://catchup.cloud/blog/images/blog14.jpg" alt="image">');
document.write('');
document.write('                        </div>');
document.write('                        <div class="story_text">');
document.write('                          <a href="https://catchup.cloud/blog/blog_what_us_tech_talent_looks_for_in_remote_work.html">');
document.write('                            <h3>What US Tech Talent Looks for in Remote Work?');
document.write('                            </h3>');
document.write('                          </a>');
document.write('                          <p>As companies and organizations continue to shift to a remote work environment...</p>');
document.write('                          <a href="https://catchup.cloud/blog/blog_what_us_tech_talent_looks_for_in_remote_work.html">READ MORE</a>');
document.write('                        </div>');
document.write('                      </div>');
document.write('                    </div>');

document.write('                    <!-- story -->');
document.write('                    <div class="col-md-4">');
document.write('                      <div class="story_box">');
document.write('                        <div class="story_img">');
document.write('                          <img src="https://catchup.cloud/blog/images/blog15.jpg" alt="image">');
document.write('');
document.write('                        </div>');
document.write('                        <div class="story_text">');
document.write('                          <a href="https://catchup.cloud/blog/blog_collaborative_communication__the_future_of_your_business.html">');
document.write('                            <h3>Collaborative communication - the future of your business');
document.write('                            </h3>');
document.write('                          </a>');
document.write('                          <p>The process of sharing information, feedback, and ideas in a way that promotes cooperation...</p>');
document.write('                          <a href="https://catchup.cloud/blog/blog_collaborative_communication__the_future_of_your_business.html">READ MORE</a>');
document.write('                        </div>');
document.write('                      </div>');
document.write('                    </div>');
document.write('');
document.write('');
document.write('                  </div>');
document.write('                </div>');



document.write('                <div class="carousel-item">');
document.write('                  <div class="row">');
document.write('');
document.write('                    <!-- story -->');
document.write('                    <div class="col-md-4">');
document.write('                      <div class="story_box">');
document.write('                        <div class="story_img">');
document.write('                          <img src="https://catchup.cloud/blog/images/blog16.jpg" alt="image">');
document.write('');
document.write('                        </div>');
document.write('                        <div class="story_text">');
document.write('                          <a href="https://catchup.cloud/blog/blog_tips_to_being_an_accountable_team_member.html">');
document.write('                            <h3>Tips to Being an Accountable Team Member');
document.write('                            </h3>');
document.write('                          </a>');
document.write('                          <p>Being a responsible teammate is vital for every successful team. It entails accepting responsibility for your duties...</p>');
document.write('                          <a href="https://catchup.cloud/blog/blog_tips_to_being_an_accountable_team_member.html">READ MORE</a>');
document.write('                        </div>');
document.write('                      </div>');
document.write('                    </div>');
document.write('');

document.write('                    <!-- story -->');
document.write('                    <div class="col-md-4">');
document.write('                      <div class="story_box">');
document.write('                        <div class="story_img">');
document.write('                          <img src="https://catchup.cloud/blog/images/blog17.jpg" alt="image">');
document.write('');
document.write('                        </div>');
document.write('                        <div class="story_text">');
document.write('                          <a href="https://catchup.cloud/blog/blog_do_this_to_make_your_organization_successful.html">');
document.write('                            <h3>Do This to Make Your Organization Successful');
document.write('                            </h3>');
document.write('                          </a>');
document.write('                          <p>Every organization has its unique set of challenges and prospects, but certain fundamental principles can help drive...</p>');
document.write('                          <a href="https://catchup.cloud/blog/blog_do_this_to_make_your_organization_successful.html">READ MORE</a>');
document.write('                        </div>');
document.write('                      </div>');
document.write('                    </div>');

document.write('                    <!-- story -->');
document.write('                    <div class="col-md-4">');
/*document.write('                      <div class="story_box">');
document.write('                        <div class="story_img">');
document.write('                          <img src="https://catchup.cloud/blog/images/blog15.jpg" alt="image">');
document.write('');
document.write('                        </div>');
document.write('                        <div class="story_text">');
document.write('                          <a href="https://catchup.cloud/blog/blog_collaborative_communication__the_future_of_your_business.html">');
document.write('                            <h3>Collaborative communication - the future of your business');
document.write('                            </h3>');
document.write('                          </a>');
document.write('                          <p>The process of sharing information, feedback, and ideas in a way that promotes cooperation...</p>');
document.write('                          <a href="https://catchup.cloud/blog/blog_collaborative_communication__the_future_of_your_business.html">READ MORE</a>');
document.write('                        </div>');
document.write('                      </div>');*/
document.write('                    </div>');
document.write('');
document.write('                  </div>');
document.write('                </div>');


document.write('');
document.write('');
document.write('');
document.write('');
document.write('              </div>');
document.write('            </div>');
document.write('          </div>');
document.write('        </div>');
document.write('      </div>');
document.write('    </section>');
