document.write("<!-- Header Start -->");
document.write("    <header>");
document.write("      <!-- container start -->");
document.write("      <div class=\"container\">");
document.write("      	<!-- navigation bar -->");
document.write("        <nav class=\"navbar navbar-expand-lg\">");
document.write("          <a class=\"navbar-brand\" href=\"http:\/\/catchup.cloud\/french\/index.html\">");
document.write("            <img src=\"http://catchup.cloud/../images/logo.png\" alt=\"image\" >");
document.write("          </a>");
document.write("          <button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\" data-target=\"#navbarSupportedContent\"");
document.write("            aria-controls=\"navbarSupportedContent\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">");
document.write("            <span class=\"navbar-toggler-icon\">");
document.write("              <!-- <i class=\"icofont-navigation-menu ico_menu\"></i> -->");
document.write("              <div class=\"toggle-wrap\">");
document.write("                <span class=\"toggle-bar\"></span>");
document.write("              </div>");
document.write("            </span>");
document.write("          </button>");
document.write("");
document.write("          <div class=\"collapse navbar-collapse\" id=\"navbarSupportedContent\">");
document.write("            <ul class=\"navbar-nav ml-auto\">");
document.write("              <li class=\"nav-item active\">");
document.write("                <a class=\"nav-link\" href=\"http://catchup.cloud/french/index.html\">Heim</a>");
document.write("              </li>");
document.write("              <li class=\"nav-item\">");
document.write("                <a class=\"nav-link\" href=\"http://catchup.cloud/french/features.html\">Funktionalitäten</a>");
document.write("              </li>");

document.write("              <li class=\"nav-item\">");
document.write("                <a class=\"nav-link\" href=\"http://catchup.cloud/french/pricing.html\">Preisgestaltung</a>");
document.write("              </li>");

document.write("              <li class=\"nav-item\">");
document.write("                <a class=\"nav-link\" href=\"http://catchup.cloud/french/whycatchup.html\">Warum CatchUpp</a>");
document.write("              </li>");
document.write("              <!-- secondery menu start -->");
document.write("              <li class=\"nav-item has_dropdown\">");
document.write("                <a class=\"nav-link\" href=\"#\">Anwendungsfälle</a>");
document.write("                <span class=\"drp_btn\"><i class=\"icofont-rounded-down\"></i></span>");
document.write("                <div class=\"sub_menu\">");
document.write("                  <ul>");
document.write("                    <li><a href=\"http://catchup.cloud/french/usecases.html\">Dienstleistungsbranche</a></li>");
document.write("                    <li><a href=\"http://catchup.cloud/french/usecases.html#it_companies\">IT-Unternehmen</a></li>");
document.write("                    <li><a href=\"http://catchup.cloud/french/usecases.html#digital_agencies\">Digitale Agenturen</a></li>");
document.write("                    <li><a href=\"http://catchup.cloud/french/usecases.html#marketing_firms\">Marketingfirmen</a></li>");
document.write("                    <li><a href=\"http://catchup.cloud/french/usecases.html#law_firms\">Anwaltskanzleien</a></li>                    ");
document.write("                  </ul>");
document.write("                </div>");
document.write("              </li>");
document.write("              <!-- secondery menu end -->");
document.write("");

document.write("              ");
document.write("              <!-- secondery menu start -->");
document.write("              <li class=\"nav-item has_dropdown\">");
document.write("                <a class=\"nav-link\" href=\"#\">Ressourcen</a>");
document.write("                <span class=\"drp_btn\"><i class=\"icofont-rounded-down\"></i></span>");
document.write("                <div class=\"sub_menu\">");
document.write("                  <ul>");
document.write("                    <li><a href=\"http://catchup.cloud/french/blog/index.html\">Blog</a></li>");
document.write("                    <li><a href=\"http://catchup.cloud/french/docs/index.html\">Dokumentation</a></li>");
document.write("                    <li><a href=\"http://catchup.cloud/french/integrations.html\">Integrationen</a></li>");
document.write("                    <li><a href=\"http://catchup.cloud/french/faq.html\">Häufig gestellte fragen</a></li>");
document.write("                    <li><a href=\"http://catchup.cloud/french/contact.html\">Kontakt</a></li>");

document.write("                  </ul>");
document.write("                </div>");
document.write("              </li>");
document.write("              <!-- secondery menu end -->");
document.write("              ");
document.write("              ");
document.write("              <li class=\"nav-item\">");
document.write("                <a class=\"nav-link\" href=\"https://dashboard.catchup.cloud\/accounts\/login\/?lang=de\">Einloggen</a>");
document.write("              </li>");
document.write("              <li class=\"nav-item\">");
document.write("                <a class=\"nav-link dark_btn\" href=\"https://dashboard.catchup.cloud\/accounts\/signup\/?lang=de\">ANMELDEN</a>");
document.write("              </li>");
document.write("            </ul>");
document.write("          </div>");
document.write("        </nav>");
document.write("        <!-- navigation end -->");
document.write("      </div>");
document.write("      <!-- container end -->");
document.write("    </header>");
