document.write('<section class="row_am latest_story blog_list_story">');
document.write('      <div class="container">');
document.write('        <div class="row">');
document.write('          <div class="col-6">');
document.write('            <h2 class="mb-3">Latest from Blog</h2>');
document.write('          </div>');
document.write('          <div class="col-6 text-right">');
document.write('            <a class="btn btn-primary mb-3 mr-1" href="#carouselExampleIndicators2" role="button" data-slide="prev"');
document.write('              style="background-color: #32236F; border-color: #32236F;">');
document.write('              <i class="fa fa-arrow-left"></i>');
document.write('            </a>');
document.write('            <a class="btn btn-primary mb-3 " href="#carouselExampleIndicators2" role="button" data-slide="next"');
document.write('              style="background-color: #32236F; border-color: #32236F;">');
document.write('              <i class="fa fa-arrow-right"></i>');
document.write('            </a>');
document.write('          </div>');
document.write('          <div class="col-12">');
document.write('            <div id="carouselExampleIndicators2" class="carousel slide" data-ride="carousel">');
document.write('');
document.write('              <div class="carousel-inner">');
document.write('');
document.write('');
document.write('                <div class="carousel-item active">');
document.write('                  <div class="row">');
document.write('');
document.write('                    <!-- story -->');
document.write('                    <div class="col-md-4">');
document.write('                      <div class="story_box">');
document.write('                        <div class="story_img">');
document.write('                          <img src="https://catchup.cloud/spanish/blog/images/blog1.jpg" alt="image">');
document.write('');
document.write('                        </div>');
document.write('                        <div class="story_text">');
document.write('                          <a href="https://catchup.cloud/spanish/blog/blog_how_project_management_tool_can_enhance_office_productivity.html">');
document.write('                            <h3>¿Cómo una herramienta de gestión de proyectos puede mejorar la productividad de su oficina?);');
document.write('                            </h3>');
document.write('                          </a>');
document.write('                          <p>En el mundo empresarial actual, la gestión eficaz de proyectos es esencial para el éxito...</p>');
document.write('                          <a href="https://catchup.cloud/spanish/blog/blog_how_project_management_tool_can_enhance_office_productivity.html">LEER MÁS</a>');
document.write('                        </div>');
document.write('                      </div>');
document.write('                    </div>');
document.write('');
document.write('                    <!-- story -->');
document.write('                    <div class="col-md-4">');
document.write('                      <div class="story_box">');
document.write('                        <div class="story_img">');
document.write('                          <img src="https://catchup.cloud/spanish/blog/images/blog2.jpg" alt="image">');
document.write('');
document.write('                        </div>');
document.write('                        <div class="story_text">');
document.write('                          <a href="https://catchup.cloud/spanish/blog/blog_what_features_to_look_for_in_project_management_tool.html">');
document.write('                            <h3>¿Qué características buscar en una herramienta de gestión de proyectos?');
document.write('                            </h3>');
document.write('                          </a>');
document.write('                          <p>Para garantizar la máxima eficiencia, se deben considerar ciertas características imprescindibles al');
document.write('                            seleccionar una herramienta de gestión de proyectos...');
document.write('                          </p>');
document.write('                          <a href="https://catchup.cloud/spanish/blog/blog_what_features_to_look_for_in_project_management_tool.html">LEER MÁS</a>');
document.write('                        </div>');
document.write('                      </div>');
document.write('                    </div>');
document.write('');
document.write('                    <!-- story -->');
document.write('                    <div class="col-md-4">');
document.write('                      <div class="story_box">');
document.write('                        <div class="story_img">');
document.write('                          <img src="https://catchup.cloud/spanish/blog/images/blog3.jpg" alt="image">');
document.write('');
document.write('                        </div>');
document.write('                        <div class="story_text">');
document.write('                          <a href="https://catchup.cloud/spanish/blog/blog_why_you_should_use_a_project_management_tool.html">');
document.write('                            <h3>¿Por qué debería utilizar una herramienta de gestión de proyectos?');
document.write('                            </h3>');
document.write('                          </a>');
document.write('                          <p>Un sistema de gestión de proyectos es una herramienta valiosa para cualquier organización.');
document.write('                            Puede ayudarlo a optimizar su flujo de trabajo...');
document.write('                          </p>');
document.write('                          <a href="https://catchup.cloud/spanish/blog/blog_why_you_should_use_a_project_management_tool.html">LEER MÁS</a>');
document.write('                        </div>');
document.write('                      </div>');
document.write('                    </div>');
document.write('');
document.write('');
document.write('                  </div>');
document.write('                </div>');
document.write('');
document.write('                <div class="carousel-item">');
document.write('                  <div class="row">');
document.write('');
document.write('                    <!-- story -->');
document.write('                    <div class="col-md-4">');
document.write('                      <div class="story_box">');
document.write('                        <div class="story_img">');
document.write('                          <img src="https://catchup.cloud/spanish/blog/images/blog6.jpg" alt="image">');
document.write('');
document.write('                        </div>');
document.write('                        <div class="story_text">');
document.write('                          <a href="https://catchup.cloud/spanish/blog/blog_how_kanban_helps_teams_be_productive.html">');
document.write('                            <h3>¿Cómo ayuda Kanban a los equipos a ser productivos?');
document.write('                            </h3>');
document.write('                          </a>');
document.write('                          <p>Kanban es una metodología para planificar, programar y mejorar el trabajo en todos los sistemas..</p>');
document.write('                          <a href="https://catchup.cloud/spanish/blog/blog_how_kanban_helps_teams_be_productive.html">LEER MÁS</a>');
document.write('                        </div>');
document.write('                      </div>');
document.write('                    </div>');
document.write('');
document.write('                    <!-- story -->');
document.write('                    <div class="col-md-4">');
document.write('                      <div class="story_box">');
document.write('                        <div class="story_img">');
document.write('                          <img src="https://catchup.cloud/spanish/blog/images/blog5.jpg" alt="image">');
document.write('');
document.write('                        </div>');
document.write('                        <div class="story_text">');
document.write('                          <a href="https://catchup.cloud/spanish/blog/blog_what_is_a_project_management_software.html">');
document.write('                            <h3>¿Qué es un software de gestión de proyectos y por qué lo necesita?');
document.write('                            </h3>');
document.write('                          </a>');
document.write('                          <p>El software de gestión de proyectos ayuda a las organizaciones a planificar...</p>');
document.write('                          <a href="https://catchup.cloud/spanish/blog/blog_what_is_a_project_management_software.html">LEER MÁS</a>');
document.write('                        </div>');
document.write('                      </div>');
document.write('                    </div>');
document.write('');
document.write('                    <!-- story -->');
document.write('                    <div class="col-md-4">');
document.write('                      <div class="story_box">');
document.write('                        <div class="story_img">');
document.write('                          <img src="https://catchup.cloud/spanish/blog/images/blog4.jpg" alt="image">');
document.write('');
document.write('                        </div>');
document.write('                        <div class="story_text">');
document.write('                          <a href="https://catchup.cloud/spanish/blog/blog_your_guide_to_effective_project_management.html">');
document.write('                            <h3>Su guía para la gestión eficaz de proyectos');
document.write('                            </h3>');
document.write('                          </a>');
document.write('                          <p>Un proyecto es una colección de tareas que deben completarse en un marco de tiempo específico...</p>');
document.write('                          <a href="https://catchup.cloud/spanish/blog/blog_your_guide_to_effective_project_management.html">LEER MÁS</a>');
document.write('                        </div>');
document.write('                      </div>');
document.write('                    </div>');
document.write('');
document.write('');
document.write('                  </div>');
document.write('                </div>');
document.write('');
document.write('                <div class="carousel-item">');
document.write('                  <div class="row">');
document.write('');
document.write('                    <!-- story -->');
document.write('                    <div class="col-md-4">');
document.write('                      <div class="story_box">');
document.write('                        <div class="story_img">');
document.write('                          <img src="https://catchup.cloud/spanish/blog/images/blog9.jpg" alt="image">');
document.write('');
document.write('                        </div>');
document.write('                        <div class="story_text">');
document.write('                          <a href="https://catchup.cloud/spanish/blog/blog_top_5_tips_for_effective_project_management.html">');
document.write('                            <h3>Los 5 mejores consejos para una gestión de proyectos eficaz');
document.write('                            </h3>');
document.write('                          </a>');
document.write('                          <p>Obtener servicios y productos de calidad entregados dentro de un límite de tiempo y presupuesto dados');
document.write('                            es la necesidad de cualquier negocio...</p>');
document.write('                          <a href="https://catchup.cloud/spanish/blog/blog_top_5_tips_for_effective_project_management.html">LEER MÁS</a>');
document.write('                        </div>');
document.write('                      </div>');
document.write('                    </div>');
document.write('');
document.write('                    <!-- story -->');
document.write('                    <div class="col-md-4">');
document.write('                      <div class="story_box">');
document.write('                        <div class="story_img">');
document.write('                          <img src="https://catchup.cloud/spanish/blog/images/blog8.jpg" alt="image">');
document.write('');
document.write('                        </div>');
document.write('                        <div class="story_text">');
document.write('                          <a href="https://catchup.cloud/spanish/blog/blog_top_5_best_practices_for_remote_work_management.html">');
document.write('                            <h3>Las 5 mejores prácticas para la gestión del trabajo remoto');
document.write('                            </h3>');
document.write('                          </a>');
document.write('                          <p>El trabajo remoto se ha convertido en una norma en el mundo actual, y es fundamental para las organizaciones...');
document.write('                          </p>');
document.write('                          <a href="https://catchup.cloud/spanish/blog/blog_top_5_best_practices_for_remote_work_management.html">LEER MÁS</a>');
document.write('                        </div>');
document.write('                      </div>');
document.write('                    </div>');
document.write('');
document.write('                    <!-- story -->');
document.write('                    <div class="col-md-4">');
document.write('                      <div class="story_box">');
document.write('                        <div class="story_img">');
document.write('                          <img src="https://catchup.cloud/spanish/blog/images/blog7.jpg" alt="image">');
document.write('');
document.write('                        </div>');
document.write('                        <div class="story_text">');
document.write('                          <a href="https://catchup.cloud/spanish/blog/blog_top_10_remote_work_management_mistakes_and_how_to_avoid_them.html">');
document.write('                            <h3>Los 10 principales errores de gestión del trabajo remoto y cómo evitarlos');
document.write('                            </h3>');
document.write('                          </a>');
document.write('                          <p>A medida que el trabajo remoto se vuelve más popular, un número creciente de...</p>');
document.write('                          <a href="https://catchup.cloud/spanish/blog/blog_top_10_remote_work_management_mistakes_and_how_to_avoid_them.html">LEER MÁS</a>');
document.write('                        </div>');
document.write('                      </div>');
document.write('                    </div>');
document.write('');
document.write('');
document.write('                  </div>');
document.write('                </div>');
document.write('');
document.write('                <div class="carousel-item">');
document.write('                  <div class="row">');
document.write('');
document.write('                    <!-- story -->');
document.write('                    <div class="col-md-4">');
document.write('                      <div class="story_box">');
document.write('                        <div class="story_img">');
document.write('                          <img src="https://catchup.cloud/spanish/blog/images/blog12.jpg" alt="image">');
document.write('');
document.write('                        </div>');
document.write('                        <div class="story_text">');
document.write('                          <a href="https://catchup.cloud/spanish/blog/blog_understanding_cobra_typology_for_brand_growth.html">');
document.write('                            <h3>Comprender la tipología de COBRA (comportamientos relacionados con la marca en línea');
document.write('                              de los clientes) para el crecimiento de la marca');
document.write('                            </h3>');
document.write('                          </a>');
document.write('                          <p>Empresas activas en el espacio digital...</p>');
document.write('                          <a href="https://catchup.cloud/spanish/blog/blog_understanding_cobra_typology_for_brand_growth.html">LEER MÁS</a>');
document.write('                        </div>');
document.write('                      </div>');
document.write('                    </div>');
document.write('');
document.write('');
document.write('                    <!-- story -->');
document.write('                    <div class="col-md-4">');
document.write('                      <div class="story_box">');
document.write('                        <div class="story_img">');
document.write('                          <img src="https://catchup.cloud/spanish/blog/images/blog11.jpg" alt="image">');
document.write('');
document.write('                        </div>');
document.write('                        <div class="story_text">');
document.write('                          <a');
document.write('                            href="https://catchup.cloud/spanish/blog/blog_how_a_good_project_management_tool_helps_manage_transformation.html">');
document.write('                            <h3>Cómo una buena herramienta de gestión de proyectos ayuda a gestionar los gastos de transformación');
document.write('                            </h3>');
document.write('                          </a>');
document.write('                          <p>Los gastos de transformación son...</p>');
document.write('                          <a');
document.write('                            href="https://catchup.cloud/spanish/blog/blog_how_a_good_project_management_tool_helps_manage_transformation.html">LEER');
document.write('                            MÁS</a>');
document.write('                        </div>');
document.write('                      </div>');
document.write('                    </div>');
document.write('');
document.write('                    <!-- story -->');
document.write('                    <div class="col-md-4">');
document.write('                      <div class="story_box">');
document.write('                        <div class="story_img">');
document.write('                          <img src="https://catchup.cloud/spanish/blog/images/blog10.jpg" alt="image">');
document.write('');
document.write('                        </div>');
document.write('                        <div class="story_text">');
document.write('                          <a href="https://catchup.cloud/spanish/blog/blog_why_leading_companies_are_prioritizing_digital_transformation.html">');
document.write('                            <h3>¿Por qué las empresas líderes priorizan la transformación digital?');
document.write('                            </h3>');
document.write('                          </a>');
document.write('                          <p>La transformación digital se está convirtiendo cada vez más en una prioridad para las empresas...</p>');
document.write('                          <a href="https://catchup.cloud/spanish/blog/blog_why_leading_companies_are_prioritizing_digital_transformation.html">LEER');
document.write('                            MÁS</a>');
document.write('                        </div>');
document.write('                      </div>');
document.write('                    </div>');
document.write('');
document.write('');
document.write('                  </div>');
document.write('                </div>');
document.write('');
document.write('                <div class="carousel-item">');
document.write('                  <div class="row">');
document.write('');
document.write('                    <!-- story -->');
document.write('                    <div class="col-md-4">');
document.write('                      <div class="story_box">');
document.write('                        <div class="story_img">');
document.write('                          <img src="https://catchup.cloud/spanish/blog/images/blog13.jpg" alt="image">');
document.write('');
document.write('                        </div>');
document.write('                        <div class="story_text">');
document.write('                          <a href="https://catchup.cloud/spanish/blog/blog_the_future_of_work_after_pandemic.html">');
document.write('                            <h3>El futuro del trabajo después de la pandemia');
document.write('                            </h3>');
document.write('                          </a>');
document.write('                          <p>La pandemia de COVID-19 fue testigo de una transformación significativa en la forma en que');
document.write('                            trabajamos, vivimos y pensamos sobre nuestro futuro...</p>');
document.write('                          <a href="https://catchup.cloud/spanish/blog/blog_the_future_of_work_after_pandemic.html">LEER MÁS</a>');
document.write('                        </div>');
document.write('                      </div>');
document.write('                    </div>');
document.write('');

document.write('                    <!-- story -->');
document.write('                    <div class="col-md-4">');
document.write('                      <div class="story_box">');
document.write('                        <div class="story_img">');
document.write('                          <img src="https://catchup.cloud/spanish/blog/images/blog14.jpg" alt="image">');
document.write('');
document.write('                        </div>');
document.write('                        <div class="story_text">');
document.write('                          <a href="https://catchup.cloud/spanish/blog/blog_what_us_tech_talent_looks_for_in_remote_work.html">');
document.write('                            <h3>¿Qué busca el talento tecnológico estadounidense en el trabajo remoto?');
document.write('                            </h3>');
document.write('                          </a>');
document.write('                          <p>A medida que las empresas y organizaciones continúan cambiando a un entorno de trabajo remoto...</p>');
document.write('                          <a href="https://catchup.cloud/spanish/blog/blog_what_us_tech_talent_looks_for_in_remote_work.html">LEER MÁS</a>');
document.write('                        </div>');
document.write('                      </div>');
document.write('                    </div>');

document.write('                    <!-- story -->');
document.write('                    <div class="col-md-4">');
document.write('                      <div class="story_box">');
document.write('                        <div class="story_img">');
document.write('                          <img src="https://catchup.cloud/spanish/blog/images/blog15.jpg" alt="image">');
document.write('');
document.write('                        </div>');
document.write('                        <div class="story_text">');
document.write('                          <a href="https://catchup.cloud/spanish/blog/blog_collaborative_communication_the_future_of_your_business.html">');
document.write('                            <h3>Comunicación colaborativa: el futuro de su negocio');
document.write('                            </h3>');
document.write('                          </a>');
document.write('                          <p>El proceso de compartir información, comentarios e ideas de una manera que promueva la cooperación...</p>');
document.write('                          <a href="https://catchup.cloud/spanish/blog/blog_collaborative_communication_the_future_of_your_business.html">LEER MÁS</a>');
document.write('                        </div>');
document.write('                      </div>');
document.write('                    </div>');
document.write('');
document.write('');
document.write('                  </div>');
document.write('                </div>');



document.write('                <div class="carousel-item">');
document.write('                  <div class="row">');
document.write('');
document.write('                    <!-- story -->');
document.write('                    <div class="col-md-4">');
document.write('                      <div class="story_box">');
document.write('                        <div class="story_img">');
document.write('                          <img src="https://catchup.cloud/spanish/blog/images/blog16.jpg" alt="image">');
document.write('');
document.write('                        </div>');
document.write('                        <div class="story_text">');
document.write('                          <a href="https://catchup.cloud/spanish/blog/blog_tips_to_being_an_accountable_team_member.html">');
document.write('                            <h3>Consejos para ser un miembro responsable del equipo');
document.write('                            </h3>');
document.write('                          </a>');
document.write('                          <p>Ser un compañero de equipo responsable es vital para todo equipo exitoso. Implica aceptar la responsabilidad de sus deberes...</p>');
document.write('                          <a href="https://catchup.cloud/spanish/blog/blog_tips_to_being_an_accountable_team_member.html">LEER MÁS</a>');
document.write('                        </div>');
document.write('                      </div>');
document.write('                    </div>');
document.write('');

document.write('                    <!-- story -->');
document.write('                    <div class="col-md-4">');
document.write('                      <div class="story_box">');
document.write('                        <div class="story_img">');
document.write('                          <img src="https://catchup.cloud/spanish/blog/images/blog17.jpg" alt="image">');
document.write('');
document.write('                        </div>');
document.write('                        <div class="story_text">');
document.write('                          <a href="https://catchup.cloud/spanish/blog/blog_do_this_to_make_your_organization_successful.html">');
document.write('                            <h3>Haga esto para que su organización sea exitosa');
document.write('                            </h3>');
document.write('                          </a>');
document.write('                          <p>Cada organización tiene su conjunto único de desafíos y perspectivas, pero ciertos principios fundamentales pueden ayudar a impulsar...</p>');
document.write('                          <a href="https://catchup.cloud/spanish/blog/blog_do_this_to_make_your_organization_successful.html">LEER MÁS</a>');
document.write('                        </div>');
document.write('                      </div>');
document.write('                    </div>');

document.write('                    <!-- story -->');
document.write('                    <div class="col-md-4">');
document.write('                      <div class="story_box">');
document.write('                        <div class="story_img">');
document.write('                          <img src="https://catchup.cloud/spanish/blog/images/blog18.jpg" alt="image">');
document.write('');
document.write('                        </div>');
document.write('                        <div class="story_text">');
document.write('                          <a href="https://catchup.cloud/spanish/blog/blog_finding_the_best_project_management_software_using_the_okr.html">');
document.write('                            <h3>Encontrar el mejor software de gestión de proyectos utilizando el marco OKR');
document.write('                            </h3>');
document.write('                          </a>');
document.write('                          <p>OKR (Objetivos y resultados clave) es un paradigma de establecimiento de metas que ha ganado...</p>');
document.write('                          <a href="https://catchup.cloud/spanish/blog/blog_finding_the_best_project_management_software_using_the_okr.html">LEER MÁS</a>');
document.write('                        </div>');
document.write('                      </div>');
document.write('                    </div>');
document.write('');
document.write('                  </div>');
document.write('                </div>');


document.write('                <div class="carousel-item">');
document.write('                  <div class="row">');
document.write('');
document.write('                    <!-- story -->');
document.write('                    <div class="col-md-4">');
document.write('                      <div class="story_box">');
document.write('                        <div class="story_img">');
document.write('                          <img src="https://catchup.cloud/spanish/blog/images/blog19.jpg" alt="image">');
document.write('');
document.write('                        </div>');
document.write('                        <div class="story_text">');
document.write('                          <a href="https://catchup.cloud/spanish/blog/blog_ai_tools_like_chat_gpt_google_bard_are_about_to_revolutionize.html">');
document.write('                            <h3>Herramientas de IA como ChatGPT y Google Bard están a punto de revolucionar la gestión de proyectos');
document.write('                            </h3>');
document.write('                          </a>');
document.write('                          <p>La Inteligencia Artificial (IA) ya ha transformado industrias en varios sectores al automatizar rutinas...</p>');
document.write('                          <a href="https://catchup.cloud/spanish/blog/blog_ai_tools_like_chat_gpt_google_bard_are_about_to_revolutionize.html">LEER MÁS</a>');
document.write('                        </div>');
document.write('                      </div>');
document.write('                    </div>');
document.write('');

document.write('                    <!-- story -->');
document.write('                    <div class="col-md-4">');
document.write('                      <div class="story_box">');
document.write('                        <div class="story_img">');
document.write('                          <img src="https://catchup.cloud/spanish/blog/images/blog20.jpg" alt="image">');
document.write('');
document.write('                        </div>');
document.write('                        <div class="story_text">');
document.write('                          <a href="https://catchup.cloud/spanish/blog/blog_chat_gpt_vs_your_job_vs_project_management_software_solutions.html">');
document.write('                            <h3>ChatGPT frente a su trabajo frente a soluciones de software de gestión de proyectos: ¿es tiempo de guerra?');
document.write('                            </h3>');
document.write('                          </a>');
document.write('                          <p>Con todas las tendencias, las cosas virales de ChatGPT en línea, y la gente que dice que causará despidos masivos...</p>');
document.write('                          <a href="https://catchup.cloud/spanish/blog/blog_chat_gpt_vs_your_job_vs_project_management_software_solutions.html">LEER MÁS</a>');
document.write('                        </div>');
document.write('                      </div>');
document.write('                    </div>');

document.write('                    <!-- story -->');
document.write('                    <div class="col-md-4">');
document.write('                      <div class="story_box">');
document.write('                        <div class="story_img">');
document.write('                          <img src="https://catchup.cloud/spanish/blog/images/diversity.jpg" alt="image">');
document.write('');
document.write('                        </div>');
document.write('                        <div class="story_text">');
document.write('                          <a href="https://catchup.cloud/spanish/blog/blog-diversity-equity-and-inclusion.html">');
document.write('                            <h3>Diversidad, equidad e inclusión (DEI): importancia e implementación (DEI - Diversity, Equity, and Inclusion)');
document.write('                            </h3>');
document.write('                          </a>');
document.write('                          <p>La diversidad, la equidad y la inclusión (DEI) son elementos vitales para el éxito de cualquier organización...</p>');
document.write('                          <a href="https://catchup.cloud/spanish/blog/blog-diversity-equity-and-inclusion.html">LEER MÁS</a>');
document.write('                        </div>');
document.write('                      </div>');
document.write('                    </div>');
document.write('');
document.write('                  </div>');
document.write('                </div>');

document.write('                <div class="carousel-item">');
document.write('                  <div class="row">');
document.write('');
document.write('                    <!-- story -->');
document.write('                    <div class="col-md-4">');
document.write('                      <div class="story_box">');
document.write('                        <div class="story_img">');
document.write('                          <img src="https://catchup.cloud/spanish/blog/images/blog-tech.jpg" alt="image">');
document.write('');
document.write('                        </div>');
document.write('                        <div class="story_text">');
document.write('                          <a href="https://catchup.cloud/spanish/blog/blog-leveraging-technology-for-effective-project-management.html">');
document.write('                            <h3>Aprovechamiento de la tecnología para una gestión eficaz de proyectos: estrategias clave y mejores prácticas');
document.write('                            </h3>');
document.write('                          </a>');
document.write('                          <p>Los avances tecnológicos acelerados de hoy han tocado la mayoría de las esferas del trabajo y la vida...</p>');
document.write('                          <a href="https://catchup.cloud/spanish/blog/blog-leveraging-technology-for-effective-project-management.html">LEER MÁS</a>');
document.write('                        </div>');
document.write('                      </div>');
document.write('                    </div>');
document.write('');

document.write('                    <!-- story -->');
document.write('                    <div class="col-md-4">');
document.write('                      <div class="story_box">');
document.write('                        <div class="story_img">');
document.write('                          <img src="https://catchup.cloud/spanish/blog/images/blog-ai.jpg" alt="image">');
document.write('');
document.write('                        </div>');
document.write('                        <div class="story_text">');
document.write('                          <a href="https://catchup.cloud/spanish/blog/blog-impact-of-automation-and-artificial-intelligence-technologies-on-project-management-practices.html">');
document.write('                            <h3>Impacto de las tecnologías de automatización e inteligencia artificial (IA) en las prácticas de gestión de proyectos');
document.write('                            </h3>');
document.write('                          </a>');
document.write('                          <p>Los rápidos avances en la tecnología de automatización e inteligencia artificial...</p>');
document.write('                          <a href="https://catchup.cloud/spanish/blog/blog-impact-of-automation-and-artificial-intelligence-technologies-on-project-management-practices.html">LEER MÁS</a>');
document.write('                        </div>');
document.write('                      </div>');
document.write('                    </div>');

document.write('                    <!-- story -->');
document.write('                    <div class="col-md-4">');
document.write('                      <div class="story_box">');
document.write('                        <div class="story_img">');
document.write('                          <img src="https://catchup.cloud/spanish/blog/images/blog-kanban.jpg" alt="image">');
document.write('');
document.write('                        </div>');
document.write('                        <div class="story_text">');
document.write('                          <a href="https://catchup.cloud/spanish/blog/blog-kanban-board-vs-gantt-charts.html">');
document.write('                            <h3>Tablero Kanban vs diagramas de Gantt');
document.write('                            </h3>');
document.write('                          </a>');
document.write('                          <p>El tablero Kanban y los diagramas de Gantt son herramientas populares que han revolucionado...</p>');
document.write('                          <a href="https://catchup.cloud/spanish/blog/blog-kanban-board-vs-gantt-charts.html">LEER MÁS</a>');
document.write('                        </div>');
document.write('                      </div>');
document.write('                    </div>');
document.write('');
document.write('                  </div>');
document.write('                </div>');

document.write('                <div class="carousel-item">');
document.write('                  <div class="row">');
document.write('');
document.write('                    <!-- story -->');
document.write('                    <div class="col-md-4">');
document.write('                      <div class="story_box">');
document.write('                        <div class="story_img">');
document.write('                          <img src="https://catchup.cloud/spanish/blog/images/blog-effective.jpg" alt="image">');
document.write('');
document.write('                        </div>');
document.write('                        <div class="story_text">');
document.write('                          <a href="https://catchup.cloud/spanish/blog/blog-the-evolution-of-project-management-tools.html">');
document.write('                            <h3>La evolución de las herramientas de gestión de proyectos: potenciando el éxito a través de los avances tecnológicos');
document.write('                            </h3>');
document.write('                          </a>');
document.write('                          <p>La gestión eficaz de proyectos siempre ha sido esencial para que las organizaciones se mantengan competitivas...</p>');
document.write('                          <a href="https://catchup.cloud/spanish/blog/blog-the-evolution-of-project-management-tools.html">LEER MÁS</a>');
document.write('                        </div>');
document.write('                      </div>');
document.write('                    </div>');
document.write('');

document.write('                    <!-- story -->');
document.write('                    <div class="col-md-4">');
document.write('                      <div class="story_box">');
document.write('                        <div class="story_img">');
document.write('                          <img src="https://catchup.cloud/spanish/blog/images/blog22.jpg" alt="image">');
document.write('');
document.write('                        </div>');
document.write('                        <div class="story_text">');
document.write('                          <a href="https://catchup.cloud/spanish/blog/blog-data-breach-prevention-how-iso-27001:2022-keeps-your-data-safe.html">');
document.write('                            <h3>Prevención de violaciones de datos: ¿Cómo ISO 27001:2022 mantiene sus datos seguros?');
document.write('                            </h3>');
document.write('                          </a>');
document.write('                          <p>El activo más importante del mundo digital actual son los datos, por lo que su protección contra posibles...</p>');
document.write('                          <a href="https://catchup.cloud/spanish/blog/blog-data-breach-prevention-how-iso-27001:2022-keeps-your-data-safe.html">LEER MÁS</a>');
document.write('                        </div>');
document.write('                      </div>');
document.write('                    </div>');

// document.write('                    <!-- story -->');
// document.write('                    <div class="col-md-4">');
// document.write('                      <div class="story_box">');
// document.write('                        <div class="story_img">');
// document.write('                          <img src="https://catchup.cloud/spanish/blog/images/diversity.jpg" alt="image">');
// document.write('');
// document.write('                        </div>');
// document.write('                        <div class="story_text">');
// document.write('                          <a href="https://catchup.cloud/spanish/blog/blog-diversity-equity-and-inclusion.html">');
// document.write('                            <h3>Diversidad, equidad e inclusión (DEI): importancia e implementación (DEI - Diversity, Equity, and Inclusion)');
// document.write('                            </h3>');
// document.write('                          </a>');
// document.write('                          <p>La diversidad, la equidad y la inclusión (DEI) son elementos vitales para el éxito de cualquier organización...</p>');
// document.write('                          <a href="https://catchup.cloud/spanish/blog/blog-diversity-equity-and-inclusion.html">LEER MÁS</a>');
// document.write('                        </div>');
// document.write('                      </div>');
// document.write('                    </div>');
document.write('');
document.write('                  </div>');
document.write('                </div>');


document.write('');
document.write('');
document.write('');
document.write('');
document.write('              </div>');
document.write('            </div>');
document.write('          </div>');
document.write('        </div>');
document.write('      </div>');
document.write('    </section>');
