document.write("<!-- Header Start -->");
document.write("    <header>");
document.write("      <!-- container start -->");
document.write("      <div class=\"container\">");
document.write("      	<!-- navigation bar -->");
document.write("        <nav class=\"navbar navbar-expand-lg\">");
document.write("          <a class=\"navbar-brand\" href=\"http:\/\/catchup.cloud\/portuguese\/index.html\">");
document.write("            <img src=\"http://catchup.cloud/../images/logo.png\" alt=\"image\" >");
document.write("          </a>");
document.write("          <button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\" data-target=\"#navbarSupportedContent\"");
document.write("            aria-controls=\"navbarSupportedContent\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">");
document.write("            <span class=\"navbar-toggler-icon\">");
document.write("              <!-- <i class=\"icofont-navigation-menu ico_menu\"></i> -->");
document.write("              <div class=\"toggle-wrap\">");
document.write("                <span class=\"toggle-bar\"></span>");
document.write("              </div>");
document.write("            </span>");
document.write("          </button>");
document.write("");
document.write("          <div class=\"collapse navbar-collapse\" id=\"navbarSupportedContent\">");
document.write("            <ul class=\"navbar-nav ml-auto\">");
document.write("              <li class=\"nav-item active\">");
document.write("                <a class=\"nav-link\" href=\"https://catchup.cloud/portuguese/index.html\">Início</a>");
document.write("              </li>");
document.write("              <li class=\"nav-item\">");
document.write("                <a class=\"nav-link\" href=\"https://catchup.cloud/portuguese/features.html\">Característicos</a>");
document.write("              </li>");

document.write("              <li class=\"nav-item\">");
document.write("                <a class=\"nav-link\" href=\"https://catchup.cloud/portuguese/pricing.html\">Precificação</a>");
document.write("              </li>");

document.write("              <li class=\"nav-item\">");
document.write("                <a class=\"nav-link\" href=\"https://catchup.cloud/portuguese/whycatchup.html\">Por que CatchUp</a>");
document.write("              </li>");
document.write("              <!-- secondery menu start -->");
document.write("              <li class=\"nav-item has_dropdown\">");
document.write("                <a class=\"nav-link\" href=\"#\">Casos de uso</a>");
document.write("                <span class=\"drp_btn\"><i class=\"icofont-rounded-down\"></i></span>");
document.write("                <div class=\"sub_menu\">");
document.write("                  <ul>");
document.write("                    <li><a href=\"https://catchup.cloud/portuguese/usecases.html\">Indústria de serviços</a></li>");
document.write("                    <li><a href=\"https://catchup.cloud/portuguese/usecases.html#it_companies\">Empresas de TI</a></li>");
document.write("                    <li><a href=\"https://catchup.cloud/portuguese/usecases.html#digital_agencies\">Agências Digitais</a></li>");
document.write("                    <li><a href=\"https://catchup.cloud/portuguese/usecases.html#marketing_firms\">Empresas de marketing</a></li>");
document.write("                    <li><a href=\"https://catchup.cloud/portuguese/usecases.html#law_firms\">Sociedades de Advogados</a></li>                    ");
document.write("                  </ul>");
document.write("                </div>");
document.write("              </li>");
document.write("              <!-- secondery menu end -->");
document.write("");

document.write("              ");
document.write("              <!-- secondery menu start -->");
document.write("              <li class=\"nav-item has_dropdown\">");
document.write("                <a class=\"nav-link\" href=\"#\">Recursos</a>");
document.write("                <span class=\"drp_btn\"><i class=\"icofont-rounded-down\"></i></span>");
document.write("                <div class=\"sub_menu\">");
document.write("                  <ul>");
document.write("                    <li><a href=\"https://catchup.cloud/portuguese/blog/index.html\">Blog</a></li>");
document.write("                    <li><a href=\"https://catchup.cloud/docs/index.html\">Documentação</a></li>");
document.write("                    <li><a href=\"https://catchup.cloud/portuguese/integrations.html\">Integrações</a></li>");
document.write("                    <li><a href=\"https://catchup.cloud/portuguese/iso-27001.html\">ISO 27001</a></li>");
document.write("                    <li><a href=\"https://catchup.cloud/portuguese/faq.html\">Perguntas frequentes</a></li>");
document.write("                    <li><a href=\"https://catchup.cloud/portuguese/contact.html\">Contato</a></li>");

document.write("                  </ul>");
document.write("                </div>");
document.write("              </li>");
document.write("              <!-- secondery menu end -->");
document.write("              ");
document.write("              ");
document.write("              <li class=\"nav-item\">");
document.write("                <a class=\"nav-link\" href=\"https://dashboard.catchup.cloud\/accounts\/login\/?lang=pt\">Conecte-se</a>");
document.write("              </li>");
document.write("              <li class=\"nav-item\">");
document.write("                <a class=\"nav-link dark_btn\" href=\"https://dashboard.catchup.cloud\/accounts\/signup\/?lang=pt\">Registro</a>");
document.write("              </li>");
document.write("            </ul>");
document.write("          </div>");
document.write("        </nav>");
document.write("        <!-- navigation end -->");
document.write("      </div>");
document.write("      <!-- container end -->");
document.write("    </header>");
